// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/clockkeeper/ent/death"
	"github.com/shifty11/clockkeeper/ent/phase"
)

// DeathCreate is the builder for creating a Death entity.
type DeathCreate struct {
	config
	mutation *DeathMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeathCreate) SetCreatedAt(v time.Time) *DeathCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeathCreate) SetNillableCreatedAt(v *time.Time) *DeathCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeathCreate) SetUpdatedAt(v time.Time) *DeathCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeathCreate) SetNillableUpdatedAt(v *time.Time) *DeathCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPhaseID sets the "phase_id" field.
func (_c *DeathCreate) SetPhaseID(v int) *DeathCreate {
	_c.mutation.SetPhaseID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *DeathCreate) SetRoleID(v string) *DeathCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetGhostVote sets the "ghost_vote" field.
func (_c *DeathCreate) SetGhostVote(v bool) *DeathCreate {
	_c.mutation.SetGhostVote(v)
	return _c
}

// SetNillableGhostVote sets the "ghost_vote" field if the given value is not nil.
func (_c *DeathCreate) SetNillableGhostVote(v *bool) *DeathCreate {
	if v != nil {
		_c.SetGhostVote(*v)
	}
	return _c
}

// SetPhase sets the "phase" edge to the Phase entity.
func (_c *DeathCreate) SetPhase(v *Phase) *DeathCreate {
	return _c.SetPhaseID(v.ID)
}

// Mutation returns the DeathMutation object of the builder.
func (_c *DeathCreate) Mutation() *DeathMutation {
	return _c.mutation
}

// Save creates the Death in the database.
func (_c *DeathCreate) Save(ctx context.Context) (*Death, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeathCreate) SaveX(ctx context.Context) *Death {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeathCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeathCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeathCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := death.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := death.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GhostVote(); !ok {
		v := death.DefaultGhostVote
		_c.mutation.SetGhostVote(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeathCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Death.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Death.updated_at"`)}
	}
	if _, ok := _c.mutation.PhaseID(); !ok {
		return &ValidationError{Name: "phase_id", err: errors.New(`ent: missing required field "Death.phase_id"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "Death.role_id"`)}
	}
	if v, ok := _c.mutation.RoleID(); ok {
		if err := death.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "Death.role_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GhostVote(); !ok {
		return &ValidationError{Name: "ghost_vote", err: errors.New(`ent: missing required field "Death.ghost_vote"`)}
	}
	if len(_c.mutation.PhaseIDs()) == 0 {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required edge "Death.phase"`)}
	}
	return nil
}

func (_c *DeathCreate) sqlSave(ctx context.Context) (*Death, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeathCreate) createSpec() (*Death, *sqlgraph.CreateSpec) {
	var (
		_node = &Death{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(death.Table, sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(death.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(death.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(death.FieldRoleID, field.TypeString, value)
		_node.RoleID = value
	}
	if value, ok := _c.mutation.GhostVote(); ok {
		_spec.SetField(death.FieldGhostVote, field.TypeBool, value)
		_node.GhostVote = value
	}
	if nodes := _c.mutation.PhaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   death.PhaseTable,
			Columns: []string{death.PhaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PhaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeathCreateBulk is the builder for creating many Death entities in bulk.
type DeathCreateBulk struct {
	config
	err      error
	builders []*DeathCreate
}

// Save creates the Death entities in the database.
func (_c *DeathCreateBulk) Save(ctx context.Context) ([]*Death, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Death, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeathMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeathCreateBulk) SaveX(ctx context.Context) []*Death {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeathCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeathCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
