// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/clockkeeper/ent/death"
	"github.com/shifty11/clockkeeper/ent/phase"
	"github.com/shifty11/clockkeeper/ent/predicate"
)

// DeathUpdate is the builder for updating Death entities.
type DeathUpdate struct {
	config
	hooks    []Hook
	mutation *DeathMutation
}

// Where appends a list predicates to the DeathUpdate builder.
func (_u *DeathUpdate) Where(ps ...predicate.Death) *DeathUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeathUpdate) SetUpdatedAt(v time.Time) *DeathUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPhaseID sets the "phase_id" field.
func (_u *DeathUpdate) SetPhaseID(v int) *DeathUpdate {
	_u.mutation.SetPhaseID(v)
	return _u
}

// SetNillablePhaseID sets the "phase_id" field if the given value is not nil.
func (_u *DeathUpdate) SetNillablePhaseID(v *int) *DeathUpdate {
	if v != nil {
		_u.SetPhaseID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *DeathUpdate) SetRoleID(v string) *DeathUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *DeathUpdate) SetNillableRoleID(v *string) *DeathUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetGhostVote sets the "ghost_vote" field.
func (_u *DeathUpdate) SetGhostVote(v bool) *DeathUpdate {
	_u.mutation.SetGhostVote(v)
	return _u
}

// SetNillableGhostVote sets the "ghost_vote" field if the given value is not nil.
func (_u *DeathUpdate) SetNillableGhostVote(v *bool) *DeathUpdate {
	if v != nil {
		_u.SetGhostVote(*v)
	}
	return _u
}

// SetPhase sets the "phase" edge to the Phase entity.
func (_u *DeathUpdate) SetPhase(v *Phase) *DeathUpdate {
	return _u.SetPhaseID(v.ID)
}

// Mutation returns the DeathMutation object of the builder.
func (_u *DeathUpdate) Mutation() *DeathMutation {
	return _u.mutation
}

// ClearPhase clears the "phase" edge to the Phase entity.
func (_u *DeathUpdate) ClearPhase() *DeathUpdate {
	_u.mutation.ClearPhase()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeathUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeathUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeathUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeathUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeathUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := death.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeathUpdate) check() error {
	if v, ok := _u.mutation.RoleID(); ok {
		if err := death.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "Death.role_id": %w`, err)}
		}
	}
	if _u.mutation.PhaseCleared() && len(_u.mutation.PhaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Death.phase"`)
	}
	return nil
}

func (_u *DeathUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(death.Table, death.Columns, sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(death.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(death.FieldRoleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GhostVote(); ok {
		_spec.SetField(death.FieldGhostVote, field.TypeBool, value)
	}
	if _u.mutation.PhaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   death.PhaseTable,
			Columns: []string{death.PhaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   death.PhaseTable,
			Columns: []string{death.PhaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{death.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeathUpdateOne is the builder for updating a single Death entity.
type DeathUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeathMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeathUpdateOne) SetUpdatedAt(v time.Time) *DeathUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPhaseID sets the "phase_id" field.
func (_u *DeathUpdateOne) SetPhaseID(v int) *DeathUpdateOne {
	_u.mutation.SetPhaseID(v)
	return _u
}

// SetNillablePhaseID sets the "phase_id" field if the given value is not nil.
func (_u *DeathUpdateOne) SetNillablePhaseID(v *int) *DeathUpdateOne {
	if v != nil {
		_u.SetPhaseID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *DeathUpdateOne) SetRoleID(v string) *DeathUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *DeathUpdateOne) SetNillableRoleID(v *string) *DeathUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetGhostVote sets the "ghost_vote" field.
func (_u *DeathUpdateOne) SetGhostVote(v bool) *DeathUpdateOne {
	_u.mutation.SetGhostVote(v)
	return _u
}

// SetNillableGhostVote sets the "ghost_vote" field if the given value is not nil.
func (_u *DeathUpdateOne) SetNillableGhostVote(v *bool) *DeathUpdateOne {
	if v != nil {
		_u.SetGhostVote(*v)
	}
	return _u
}

// SetPhase sets the "phase" edge to the Phase entity.
func (_u *DeathUpdateOne) SetPhase(v *Phase) *DeathUpdateOne {
	return _u.SetPhaseID(v.ID)
}

// Mutation returns the DeathMutation object of the builder.
func (_u *DeathUpdateOne) Mutation() *DeathMutation {
	return _u.mutation
}

// ClearPhase clears the "phase" edge to the Phase entity.
func (_u *DeathUpdateOne) ClearPhase() *DeathUpdateOne {
	_u.mutation.ClearPhase()
	return _u
}

// Where appends a list predicates to the DeathUpdate builder.
func (_u *DeathUpdateOne) Where(ps ...predicate.Death) *DeathUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeathUpdateOne) Select(field string, fields ...string) *DeathUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Death entity.
func (_u *DeathUpdateOne) Save(ctx context.Context) (*Death, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeathUpdateOne) SaveX(ctx context.Context) *Death {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeathUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeathUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeathUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := death.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeathUpdateOne) check() error {
	if v, ok := _u.mutation.RoleID(); ok {
		if err := death.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "Death.role_id": %w`, err)}
		}
	}
	if _u.mutation.PhaseCleared() && len(_u.mutation.PhaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Death.phase"`)
	}
	return nil
}

func (_u *DeathUpdateOne) sqlSave(ctx context.Context) (_node *Death, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(death.Table, death.Columns, sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Death.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, death.FieldID)
		for _, f := range fields {
			if !death.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != death.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(death.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(death.FieldRoleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GhostVote(); ok {
		_spec.SetField(death.FieldGhostVote, field.TypeBool, value)
	}
	if _u.mutation.PhaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   death.PhaseTable,
			Columns: []string{death.PhaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   death.PhaseTable,
			Columns: []string{death.PhaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Death{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{death.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
