// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shifty11/clockkeeper/ent/death"
	"github.com/shifty11/clockkeeper/ent/phase"
)

// Death is the model entity for the Death schema.
type Death struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PhaseID holds the value of the "phase_id" field.
	PhaseID int `json:"phase_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID string `json:"role_id,omitempty"`
	// GhostVote holds the value of the "ghost_vote" field.
	GhostVote bool `json:"ghost_vote,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeathQuery when eager-loading is set.
	Edges        DeathEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeathEdges holds the relations/edges for other nodes in the graph.
type DeathEdges struct {
	// Phase holds the value of the phase edge.
	Phase *Phase `json:"phase,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PhaseOrErr returns the Phase value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeathEdges) PhaseOrErr() (*Phase, error) {
	if e.Phase != nil {
		return e.Phase, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: phase.Label}
	}
	return nil, &NotLoadedError{edge: "phase"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Death) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case death.FieldGhostVote:
			values[i] = new(sql.NullBool)
		case death.FieldID, death.FieldPhaseID:
			values[i] = new(sql.NullInt64)
		case death.FieldRoleID:
			values[i] = new(sql.NullString)
		case death.FieldCreatedAt, death.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Death fields.
func (_m *Death) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case death.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case death.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case death.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case death.FieldPhaseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field phase_id", values[i])
			} else if value.Valid {
				_m.PhaseID = int(value.Int64)
			}
		case death.FieldRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = value.String
			}
		case death.FieldGhostVote:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ghost_vote", values[i])
			} else if value.Valid {
				_m.GhostVote = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Death.
// This includes values selected through modifiers, order, etc.
func (_m *Death) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPhase queries the "phase" edge of the Death entity.
func (_m *Death) QueryPhase() *PhaseQuery {
	return NewDeathClient(_m.config).QueryPhase(_m)
}

// Update returns a builder for updating this Death.
// Note that you need to call Death.Unwrap() before calling this method if this Death
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Death) Update() *DeathUpdateOne {
	return NewDeathClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Death entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Death) Unwrap() *Death {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Death is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Death) String() string {
	var builder strings.Builder
	builder.WriteString("Death(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("phase_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PhaseID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(_m.RoleID)
	builder.WriteString(", ")
	builder.WriteString("ghost_vote=")
	builder.WriteString(fmt.Sprintf("%v", _m.GhostVote))
	builder.WriteByte(')')
	return builder.String()
}

// Deaths is a parsable slice of Death.
type Deaths []*Death
