// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/game"
	"github.com/loomi-labs/clockkeeper/ent/phase"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
	"github.com/loomi-labs/clockkeeper/ent/schema"
	"github.com/loomi-labs/clockkeeper/ent/script"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdate) SetUpdatedAt(v time.Time) *GameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *GameUpdate) SetName(v string) *GameUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GameUpdate) SetNillableName(v *string) *GameUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GameUpdate) SetUserID(v int) *GameUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GameUpdate) SetNillableUserID(v *int) *GameUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *GameUpdate) SetScriptID(v int) *GameUpdate {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *GameUpdate) SetNillableScriptID(v *int) *GameUpdate {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetPlayerCount sets the "player_count" field.
func (_u *GameUpdate) SetPlayerCount(v int) *GameUpdate {
	_u.mutation.ResetPlayerCount()
	_u.mutation.SetPlayerCount(v)
	return _u
}

// SetNillablePlayerCount sets the "player_count" field if the given value is not nil.
func (_u *GameUpdate) SetNillablePlayerCount(v *int) *GameUpdate {
	if v != nil {
		_u.SetPlayerCount(*v)
	}
	return _u
}

// AddPlayerCount adds value to the "player_count" field.
func (_u *GameUpdate) AddPlayerCount(v int) *GameUpdate {
	_u.mutation.AddPlayerCount(v)
	return _u
}

// SetTravellerCount sets the "traveller_count" field.
func (_u *GameUpdate) SetTravellerCount(v int) *GameUpdate {
	_u.mutation.ResetTravellerCount()
	_u.mutation.SetTravellerCount(v)
	return _u
}

// SetNillableTravellerCount sets the "traveller_count" field if the given value is not nil.
func (_u *GameUpdate) SetNillableTravellerCount(v *int) *GameUpdate {
	if v != nil {
		_u.SetTravellerCount(*v)
	}
	return _u
}

// AddTravellerCount adds value to the "traveller_count" field.
func (_u *GameUpdate) AddTravellerCount(v int) *GameUpdate {
	_u.mutation.AddTravellerCount(v)
	return _u
}

// SetSelectedRoles sets the "selected_roles" field.
func (_u *GameUpdate) SetSelectedRoles(v []string) *GameUpdate {
	_u.mutation.SetSelectedRoles(v)
	return _u
}

// AppendSelectedRoles appends value to the "selected_roles" field.
func (_u *GameUpdate) AppendSelectedRoles(v []string) *GameUpdate {
	_u.mutation.AppendSelectedRoles(v)
	return _u
}

// SetSelectedTravellers sets the "selected_travellers" field.
func (_u *GameUpdate) SetSelectedTravellers(v []string) *GameUpdate {
	_u.mutation.SetSelectedTravellers(v)
	return _u
}

// AppendSelectedTravellers appends value to the "selected_travellers" field.
func (_u *GameUpdate) AppendSelectedTravellers(v []string) *GameUpdate {
	_u.mutation.AppendSelectedTravellers(v)
	return _u
}

// SetExtraCharacters sets the "extra_characters" field.
func (_u *GameUpdate) SetExtraCharacters(v []string) *GameUpdate {
	_u.mutation.SetExtraCharacters(v)
	return _u
}

// AppendExtraCharacters appends value to the "extra_characters" field.
func (_u *GameUpdate) AppendExtraCharacters(v []string) *GameUpdate {
	_u.mutation.AppendExtraCharacters(v)
	return _u
}

// ClearExtraCharacters clears the value of the "extra_characters" field.
func (_u *GameUpdate) ClearExtraCharacters() *GameUpdate {
	_u.mutation.ClearExtraCharacters()
	return _u
}

// SetSelectedBluffs sets the "selected_bluffs" field.
func (_u *GameUpdate) SetSelectedBluffs(v []string) *GameUpdate {
	_u.mutation.SetSelectedBluffs(v)
	return _u
}

// AppendSelectedBluffs appends value to the "selected_bluffs" field.
func (_u *GameUpdate) AppendSelectedBluffs(v []string) *GameUpdate {
	_u.mutation.AppendSelectedBluffs(v)
	return _u
}

// ClearSelectedBluffs clears the value of the "selected_bluffs" field.
func (_u *GameUpdate) ClearSelectedBluffs() *GameUpdate {
	_u.mutation.ClearSelectedBluffs()
	return _u
}

// SetTravellerAlignments sets the "traveller_alignments" field.
func (_u *GameUpdate) SetTravellerAlignments(v map[string]schema.TravellerAlignment) *GameUpdate {
	_u.mutation.SetTravellerAlignments(v)
	return _u
}

// ClearTravellerAlignments clears the value of the "traveller_alignments" field.
func (_u *GameUpdate) ClearTravellerAlignments() *GameUpdate {
	_u.mutation.ClearTravellerAlignments()
	return _u
}

// SetGrimoirePositions sets the "grimoire_positions" field.
func (_u *GameUpdate) SetGrimoirePositions(v map[string]schema.GrimoirePosition) *GameUpdate {
	_u.mutation.SetGrimoirePositions(v)
	return _u
}

// ClearGrimoirePositions clears the value of the "grimoire_positions" field.
func (_u *GameUpdate) ClearGrimoirePositions() *GameUpdate {
	_u.mutation.ClearGrimoirePositions()
	return _u
}

// SetGrimoirePlayerNames sets the "grimoire_player_names" field.
func (_u *GameUpdate) SetGrimoirePlayerNames(v map[string]string) *GameUpdate {
	_u.mutation.SetGrimoirePlayerNames(v)
	return _u
}

// ClearGrimoirePlayerNames clears the value of the "grimoire_player_names" field.
func (_u *GameUpdate) ClearGrimoirePlayerNames() *GameUpdate {
	_u.mutation.ClearGrimoirePlayerNames()
	return _u
}

// SetGrimoireGameNotes sets the "grimoire_game_notes" field.
func (_u *GameUpdate) SetGrimoireGameNotes(v map[string]string) *GameUpdate {
	_u.mutation.SetGrimoireGameNotes(v)
	return _u
}

// ClearGrimoireGameNotes clears the value of the "grimoire_game_notes" field.
func (_u *GameUpdate) ClearGrimoireGameNotes() *GameUpdate {
	_u.mutation.ClearGrimoireGameNotes()
	return _u
}

// SetGrimoireRoundNotes sets the "grimoire_round_notes" field.
func (_u *GameUpdate) SetGrimoireRoundNotes(v map[string]string) *GameUpdate {
	_u.mutation.SetGrimoireRoundNotes(v)
	return _u
}

// ClearGrimoireRoundNotes clears the value of the "grimoire_round_notes" field.
func (_u *GameUpdate) ClearGrimoireRoundNotes() *GameUpdate {
	_u.mutation.ClearGrimoireRoundNotes()
	return _u
}

// SetBagSubstitutions sets the "bag_substitutions" field.
func (_u *GameUpdate) SetBagSubstitutions(v []schema.GameBagSubstitution) *GameUpdate {
	_u.mutation.SetBagSubstitutions(v)
	return _u
}

// AppendBagSubstitutions appends value to the "bag_substitutions" field.
func (_u *GameUpdate) AppendBagSubstitutions(v []schema.GameBagSubstitution) *GameUpdate {
	_u.mutation.AppendBagSubstitutions(v)
	return _u
}

// ClearBagSubstitutions clears the value of the "bag_substitutions" field.
func (_u *GameUpdate) ClearBagSubstitutions() *GameUpdate {
	_u.mutation.ClearBagSubstitutions()
	return _u
}

// SetGrimoireReminderAttachments sets the "grimoire_reminder_attachments" field.
func (_u *GameUpdate) SetGrimoireReminderAttachments(v map[string]string) *GameUpdate {
	_u.mutation.SetGrimoireReminderAttachments(v)
	return _u
}

// ClearGrimoireReminderAttachments clears the value of the "grimoire_reminder_attachments" field.
func (_u *GameUpdate) ClearGrimoireReminderAttachments() *GameUpdate {
	_u.mutation.ClearGrimoireReminderAttachments()
	return _u
}

// SetState sets the "state" field.
func (_u *GameUpdate) SetState(v game.State) *GameUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *GameUpdate) SetNillableState(v *game.State) *GameUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *GameUpdate) SetOwnerID(id int) *GameUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *GameUpdate) SetOwner(v *User) *GameUpdate {
	return _u.SetOwnerID(v.ID)
}

// SetScript sets the "script" edge to the Script entity.
func (_u *GameUpdate) SetScript(v *Script) *GameUpdate {
	return _u.SetScriptID(v.ID)
}

// AddPhaseIDs adds the "phases" edge to the Phase entity by IDs.
func (_u *GameUpdate) AddPhaseIDs(ids ...int) *GameUpdate {
	_u.mutation.AddPhaseIDs(ids...)
	return _u
}

// AddPhases adds the "phases" edges to the Phase entity.
func (_u *GameUpdate) AddPhases(v ...*Phase) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPhaseIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *GameUpdate) ClearOwner() *GameUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearScript clears the "script" edge to the Script entity.
func (_u *GameUpdate) ClearScript() *GameUpdate {
	_u.mutation.ClearScript()
	return _u
}

// ClearPhases clears all "phases" edges to the Phase entity.
func (_u *GameUpdate) ClearPhases() *GameUpdate {
	_u.mutation.ClearPhases()
	return _u
}

// RemovePhaseIDs removes the "phases" edge to Phase entities by IDs.
func (_u *GameUpdate) RemovePhaseIDs(ids ...int) *GameUpdate {
	_u.mutation.RemovePhaseIDs(ids...)
	return _u
}

// RemovePhases removes "phases" edges to Phase entities.
func (_u *GameUpdate) RemovePhases(v ...*Phase) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePhaseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdate) check() error {
	if v, ok := _u.mutation.PlayerCount(); ok {
		if err := game.PlayerCountValidator(v); err != nil {
			return &ValidationError{Name: "player_count", err: fmt.Errorf(`ent: validator failed for field "Game.player_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TravellerCount(); ok {
		if err := game.TravellerCountValidator(v); err != nil {
			return &ValidationError{Name: "traveller_count", err: fmt.Errorf(`ent: validator failed for field "Game.traveller_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := game.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Game.state": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Game.owner"`)
	}
	if _u.mutation.ScriptCleared() && len(_u.mutation.ScriptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Game.script"`)
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayerCount(); ok {
		_spec.SetField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerCount(); ok {
		_spec.AddField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TravellerCount(); ok {
		_spec.SetField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTravellerCount(); ok {
		_spec.AddField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SelectedRoles(); ok {
		_spec.SetField(game.FieldSelectedRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedRoles, value)
		})
	}
	if value, ok := _u.mutation.SelectedTravellers(); ok {
		_spec.SetField(game.FieldSelectedTravellers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedTravellers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedTravellers, value)
		})
	}
	if value, ok := _u.mutation.ExtraCharacters(); ok {
		_spec.SetField(game.FieldExtraCharacters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtraCharacters(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldExtraCharacters, value)
		})
	}
	if _u.mutation.ExtraCharactersCleared() {
		_spec.ClearField(game.FieldExtraCharacters, field.TypeJSON)
	}
	if value, ok := _u.mutation.SelectedBluffs(); ok {
		_spec.SetField(game.FieldSelectedBluffs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedBluffs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedBluffs, value)
		})
	}
	if _u.mutation.SelectedBluffsCleared() {
		_spec.ClearField(game.FieldSelectedBluffs, field.TypeJSON)
	}
	if value, ok := _u.mutation.TravellerAlignments(); ok {
		_spec.SetField(game.FieldTravellerAlignments, field.TypeJSON, value)
	}
	if _u.mutation.TravellerAlignmentsCleared() {
		_spec.ClearField(game.FieldTravellerAlignments, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoirePositions(); ok {
		_spec.SetField(game.FieldGrimoirePositions, field.TypeJSON, value)
	}
	if _u.mutation.GrimoirePositionsCleared() {
		_spec.ClearField(game.FieldGrimoirePositions, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoirePlayerNames(); ok {
		_spec.SetField(game.FieldGrimoirePlayerNames, field.TypeJSON, value)
	}
	if _u.mutation.GrimoirePlayerNamesCleared() {
		_spec.ClearField(game.FieldGrimoirePlayerNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoireGameNotes(); ok {
		_spec.SetField(game.FieldGrimoireGameNotes, field.TypeJSON, value)
	}
	if _u.mutation.GrimoireGameNotesCleared() {
		_spec.ClearField(game.FieldGrimoireGameNotes, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoireRoundNotes(); ok {
		_spec.SetField(game.FieldGrimoireRoundNotes, field.TypeJSON, value)
	}
	if _u.mutation.GrimoireRoundNotesCleared() {
		_spec.ClearField(game.FieldGrimoireRoundNotes, field.TypeJSON)
	}
	if value, ok := _u.mutation.BagSubstitutions(); ok {
		_spec.SetField(game.FieldBagSubstitutions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBagSubstitutions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldBagSubstitutions, value)
		})
	}
	if _u.mutation.BagSubstitutionsCleared() {
		_spec.ClearField(game.FieldBagSubstitutions, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoireReminderAttachments(); ok {
		_spec.SetField(game.FieldGrimoireReminderAttachments, field.TypeJSON, value)
	}
	if _u.mutation.GrimoireReminderAttachmentsCleared() {
		_spec.ClearField(game.FieldGrimoireReminderAttachments, field.TypeJSON)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(game.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.OwnerTable,
			Columns: []string{game.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.OwnerTable,
			Columns: []string{game.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScriptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PhasesTable,
			Columns: []string{game.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPhasesIDs(); len(nodes) > 0 && !_u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PhasesTable,
			Columns: []string{game.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PhasesTable,
			Columns: []string{game.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdateOne) SetUpdatedAt(v time.Time) *GameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *GameUpdateOne) SetName(v string) *GameUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableName(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GameUpdateOne) SetUserID(v int) *GameUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableUserID(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *GameUpdateOne) SetScriptID(v int) *GameUpdateOne {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableScriptID(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetPlayerCount sets the "player_count" field.
func (_u *GameUpdateOne) SetPlayerCount(v int) *GameUpdateOne {
	_u.mutation.ResetPlayerCount()
	_u.mutation.SetPlayerCount(v)
	return _u
}

// SetNillablePlayerCount sets the "player_count" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillablePlayerCount(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetPlayerCount(*v)
	}
	return _u
}

// AddPlayerCount adds value to the "player_count" field.
func (_u *GameUpdateOne) AddPlayerCount(v int) *GameUpdateOne {
	_u.mutation.AddPlayerCount(v)
	return _u
}

// SetTravellerCount sets the "traveller_count" field.
func (_u *GameUpdateOne) SetTravellerCount(v int) *GameUpdateOne {
	_u.mutation.ResetTravellerCount()
	_u.mutation.SetTravellerCount(v)
	return _u
}

// SetNillableTravellerCount sets the "traveller_count" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableTravellerCount(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetTravellerCount(*v)
	}
	return _u
}

// AddTravellerCount adds value to the "traveller_count" field.
func (_u *GameUpdateOne) AddTravellerCount(v int) *GameUpdateOne {
	_u.mutation.AddTravellerCount(v)
	return _u
}

// SetSelectedRoles sets the "selected_roles" field.
func (_u *GameUpdateOne) SetSelectedRoles(v []string) *GameUpdateOne {
	_u.mutation.SetSelectedRoles(v)
	return _u
}

// AppendSelectedRoles appends value to the "selected_roles" field.
func (_u *GameUpdateOne) AppendSelectedRoles(v []string) *GameUpdateOne {
	_u.mutation.AppendSelectedRoles(v)
	return _u
}

// SetSelectedTravellers sets the "selected_travellers" field.
func (_u *GameUpdateOne) SetSelectedTravellers(v []string) *GameUpdateOne {
	_u.mutation.SetSelectedTravellers(v)
	return _u
}

// AppendSelectedTravellers appends value to the "selected_travellers" field.
func (_u *GameUpdateOne) AppendSelectedTravellers(v []string) *GameUpdateOne {
	_u.mutation.AppendSelectedTravellers(v)
	return _u
}

// SetExtraCharacters sets the "extra_characters" field.
func (_u *GameUpdateOne) SetExtraCharacters(v []string) *GameUpdateOne {
	_u.mutation.SetExtraCharacters(v)
	return _u
}

// AppendExtraCharacters appends value to the "extra_characters" field.
func (_u *GameUpdateOne) AppendExtraCharacters(v []string) *GameUpdateOne {
	_u.mutation.AppendExtraCharacters(v)
	return _u
}

// ClearExtraCharacters clears the value of the "extra_characters" field.
func (_u *GameUpdateOne) ClearExtraCharacters() *GameUpdateOne {
	_u.mutation.ClearExtraCharacters()
	return _u
}

// SetSelectedBluffs sets the "selected_bluffs" field.
func (_u *GameUpdateOne) SetSelectedBluffs(v []string) *GameUpdateOne {
	_u.mutation.SetSelectedBluffs(v)
	return _u
}

// AppendSelectedBluffs appends value to the "selected_bluffs" field.
func (_u *GameUpdateOne) AppendSelectedBluffs(v []string) *GameUpdateOne {
	_u.mutation.AppendSelectedBluffs(v)
	return _u
}

// ClearSelectedBluffs clears the value of the "selected_bluffs" field.
func (_u *GameUpdateOne) ClearSelectedBluffs() *GameUpdateOne {
	_u.mutation.ClearSelectedBluffs()
	return _u
}

// SetTravellerAlignments sets the "traveller_alignments" field.
func (_u *GameUpdateOne) SetTravellerAlignments(v map[string]schema.TravellerAlignment) *GameUpdateOne {
	_u.mutation.SetTravellerAlignments(v)
	return _u
}

// ClearTravellerAlignments clears the value of the "traveller_alignments" field.
func (_u *GameUpdateOne) ClearTravellerAlignments() *GameUpdateOne {
	_u.mutation.ClearTravellerAlignments()
	return _u
}

// SetGrimoirePositions sets the "grimoire_positions" field.
func (_u *GameUpdateOne) SetGrimoirePositions(v map[string]schema.GrimoirePosition) *GameUpdateOne {
	_u.mutation.SetGrimoirePositions(v)
	return _u
}

// ClearGrimoirePositions clears the value of the "grimoire_positions" field.
func (_u *GameUpdateOne) ClearGrimoirePositions() *GameUpdateOne {
	_u.mutation.ClearGrimoirePositions()
	return _u
}

// SetGrimoirePlayerNames sets the "grimoire_player_names" field.
func (_u *GameUpdateOne) SetGrimoirePlayerNames(v map[string]string) *GameUpdateOne {
	_u.mutation.SetGrimoirePlayerNames(v)
	return _u
}

// ClearGrimoirePlayerNames clears the value of the "grimoire_player_names" field.
func (_u *GameUpdateOne) ClearGrimoirePlayerNames() *GameUpdateOne {
	_u.mutation.ClearGrimoirePlayerNames()
	return _u
}

// SetGrimoireGameNotes sets the "grimoire_game_notes" field.
func (_u *GameUpdateOne) SetGrimoireGameNotes(v map[string]string) *GameUpdateOne {
	_u.mutation.SetGrimoireGameNotes(v)
	return _u
}

// ClearGrimoireGameNotes clears the value of the "grimoire_game_notes" field.
func (_u *GameUpdateOne) ClearGrimoireGameNotes() *GameUpdateOne {
	_u.mutation.ClearGrimoireGameNotes()
	return _u
}

// SetGrimoireRoundNotes sets the "grimoire_round_notes" field.
func (_u *GameUpdateOne) SetGrimoireRoundNotes(v map[string]string) *GameUpdateOne {
	_u.mutation.SetGrimoireRoundNotes(v)
	return _u
}

// ClearGrimoireRoundNotes clears the value of the "grimoire_round_notes" field.
func (_u *GameUpdateOne) ClearGrimoireRoundNotes() *GameUpdateOne {
	_u.mutation.ClearGrimoireRoundNotes()
	return _u
}

// SetBagSubstitutions sets the "bag_substitutions" field.
func (_u *GameUpdateOne) SetBagSubstitutions(v []schema.GameBagSubstitution) *GameUpdateOne {
	_u.mutation.SetBagSubstitutions(v)
	return _u
}

// AppendBagSubstitutions appends value to the "bag_substitutions" field.
func (_u *GameUpdateOne) AppendBagSubstitutions(v []schema.GameBagSubstitution) *GameUpdateOne {
	_u.mutation.AppendBagSubstitutions(v)
	return _u
}

// ClearBagSubstitutions clears the value of the "bag_substitutions" field.
func (_u *GameUpdateOne) ClearBagSubstitutions() *GameUpdateOne {
	_u.mutation.ClearBagSubstitutions()
	return _u
}

// SetGrimoireReminderAttachments sets the "grimoire_reminder_attachments" field.
func (_u *GameUpdateOne) SetGrimoireReminderAttachments(v map[string]string) *GameUpdateOne {
	_u.mutation.SetGrimoireReminderAttachments(v)
	return _u
}

// ClearGrimoireReminderAttachments clears the value of the "grimoire_reminder_attachments" field.
func (_u *GameUpdateOne) ClearGrimoireReminderAttachments() *GameUpdateOne {
	_u.mutation.ClearGrimoireReminderAttachments()
	return _u
}

// SetState sets the "state" field.
func (_u *GameUpdateOne) SetState(v game.State) *GameUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableState(v *game.State) *GameUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *GameUpdateOne) SetOwnerID(id int) *GameUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *GameUpdateOne) SetOwner(v *User) *GameUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// SetScript sets the "script" edge to the Script entity.
func (_u *GameUpdateOne) SetScript(v *Script) *GameUpdateOne {
	return _u.SetScriptID(v.ID)
}

// AddPhaseIDs adds the "phases" edge to the Phase entity by IDs.
func (_u *GameUpdateOne) AddPhaseIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddPhaseIDs(ids...)
	return _u
}

// AddPhases adds the "phases" edges to the Phase entity.
func (_u *GameUpdateOne) AddPhases(v ...*Phase) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPhaseIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *GameUpdateOne) ClearOwner() *GameUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearScript clears the "script" edge to the Script entity.
func (_u *GameUpdateOne) ClearScript() *GameUpdateOne {
	_u.mutation.ClearScript()
	return _u
}

// ClearPhases clears all "phases" edges to the Phase entity.
func (_u *GameUpdateOne) ClearPhases() *GameUpdateOne {
	_u.mutation.ClearPhases()
	return _u
}

// RemovePhaseIDs removes the "phases" edge to Phase entities by IDs.
func (_u *GameUpdateOne) RemovePhaseIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemovePhaseIDs(ids...)
	return _u
}

// RemovePhases removes "phases" edges to Phase entities.
func (_u *GameUpdateOne) RemovePhases(v ...*Phase) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePhaseIDs(ids...)
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdateOne) check() error {
	if v, ok := _u.mutation.PlayerCount(); ok {
		if err := game.PlayerCountValidator(v); err != nil {
			return &ValidationError{Name: "player_count", err: fmt.Errorf(`ent: validator failed for field "Game.player_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TravellerCount(); ok {
		if err := game.TravellerCountValidator(v); err != nil {
			return &ValidationError{Name: "traveller_count", err: fmt.Errorf(`ent: validator failed for field "Game.traveller_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := game.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Game.state": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Game.owner"`)
	}
	if _u.mutation.ScriptCleared() && len(_u.mutation.ScriptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Game.script"`)
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayerCount(); ok {
		_spec.SetField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerCount(); ok {
		_spec.AddField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TravellerCount(); ok {
		_spec.SetField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTravellerCount(); ok {
		_spec.AddField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SelectedRoles(); ok {
		_spec.SetField(game.FieldSelectedRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedRoles, value)
		})
	}
	if value, ok := _u.mutation.SelectedTravellers(); ok {
		_spec.SetField(game.FieldSelectedTravellers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedTravellers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedTravellers, value)
		})
	}
	if value, ok := _u.mutation.ExtraCharacters(); ok {
		_spec.SetField(game.FieldExtraCharacters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExtraCharacters(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldExtraCharacters, value)
		})
	}
	if _u.mutation.ExtraCharactersCleared() {
		_spec.ClearField(game.FieldExtraCharacters, field.TypeJSON)
	}
	if value, ok := _u.mutation.SelectedBluffs(); ok {
		_spec.SetField(game.FieldSelectedBluffs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedBluffs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedBluffs, value)
		})
	}
	if _u.mutation.SelectedBluffsCleared() {
		_spec.ClearField(game.FieldSelectedBluffs, field.TypeJSON)
	}
	if value, ok := _u.mutation.TravellerAlignments(); ok {
		_spec.SetField(game.FieldTravellerAlignments, field.TypeJSON, value)
	}
	if _u.mutation.TravellerAlignmentsCleared() {
		_spec.ClearField(game.FieldTravellerAlignments, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoirePositions(); ok {
		_spec.SetField(game.FieldGrimoirePositions, field.TypeJSON, value)
	}
	if _u.mutation.GrimoirePositionsCleared() {
		_spec.ClearField(game.FieldGrimoirePositions, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoirePlayerNames(); ok {
		_spec.SetField(game.FieldGrimoirePlayerNames, field.TypeJSON, value)
	}
	if _u.mutation.GrimoirePlayerNamesCleared() {
		_spec.ClearField(game.FieldGrimoirePlayerNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoireGameNotes(); ok {
		_spec.SetField(game.FieldGrimoireGameNotes, field.TypeJSON, value)
	}
	if _u.mutation.GrimoireGameNotesCleared() {
		_spec.ClearField(game.FieldGrimoireGameNotes, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoireRoundNotes(); ok {
		_spec.SetField(game.FieldGrimoireRoundNotes, field.TypeJSON, value)
	}
	if _u.mutation.GrimoireRoundNotesCleared() {
		_spec.ClearField(game.FieldGrimoireRoundNotes, field.TypeJSON)
	}
	if value, ok := _u.mutation.BagSubstitutions(); ok {
		_spec.SetField(game.FieldBagSubstitutions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBagSubstitutions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldBagSubstitutions, value)
		})
	}
	if _u.mutation.BagSubstitutionsCleared() {
		_spec.ClearField(game.FieldBagSubstitutions, field.TypeJSON)
	}
	if value, ok := _u.mutation.GrimoireReminderAttachments(); ok {
		_spec.SetField(game.FieldGrimoireReminderAttachments, field.TypeJSON, value)
	}
	if _u.mutation.GrimoireReminderAttachmentsCleared() {
		_spec.ClearField(game.FieldGrimoireReminderAttachments, field.TypeJSON)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(game.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.OwnerTable,
			Columns: []string{game.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.OwnerTable,
			Columns: []string{game.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScriptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PhasesTable,
			Columns: []string{game.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPhasesIDs(); len(nodes) > 0 && !_u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PhasesTable,
			Columns: []string{game.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PhasesTable,
			Columns: []string{game.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
