// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/game"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
	"github.com/loomi-labs/clockkeeper/ent/script"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdate) SetUpdatedAt(v time.Time) *GameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *GameUpdate) SetScriptID(v int) *GameUpdate {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *GameUpdate) SetNillableScriptID(v *int) *GameUpdate {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetPlayerCount sets the "player_count" field.
func (_u *GameUpdate) SetPlayerCount(v int) *GameUpdate {
	_u.mutation.ResetPlayerCount()
	_u.mutation.SetPlayerCount(v)
	return _u
}

// SetNillablePlayerCount sets the "player_count" field if the given value is not nil.
func (_u *GameUpdate) SetNillablePlayerCount(v *int) *GameUpdate {
	if v != nil {
		_u.SetPlayerCount(*v)
	}
	return _u
}

// AddPlayerCount adds value to the "player_count" field.
func (_u *GameUpdate) AddPlayerCount(v int) *GameUpdate {
	_u.mutation.AddPlayerCount(v)
	return _u
}

// SetTravellerCount sets the "traveller_count" field.
func (_u *GameUpdate) SetTravellerCount(v int) *GameUpdate {
	_u.mutation.ResetTravellerCount()
	_u.mutation.SetTravellerCount(v)
	return _u
}

// SetNillableTravellerCount sets the "traveller_count" field if the given value is not nil.
func (_u *GameUpdate) SetNillableTravellerCount(v *int) *GameUpdate {
	if v != nil {
		_u.SetTravellerCount(*v)
	}
	return _u
}

// AddTravellerCount adds value to the "traveller_count" field.
func (_u *GameUpdate) AddTravellerCount(v int) *GameUpdate {
	_u.mutation.AddTravellerCount(v)
	return _u
}

// SetSelectedRoles sets the "selected_roles" field.
func (_u *GameUpdate) SetSelectedRoles(v []string) *GameUpdate {
	_u.mutation.SetSelectedRoles(v)
	return _u
}

// AppendSelectedRoles appends value to the "selected_roles" field.
func (_u *GameUpdate) AppendSelectedRoles(v []string) *GameUpdate {
	_u.mutation.AppendSelectedRoles(v)
	return _u
}

// SetSelectedTravellers sets the "selected_travellers" field.
func (_u *GameUpdate) SetSelectedTravellers(v []string) *GameUpdate {
	_u.mutation.SetSelectedTravellers(v)
	return _u
}

// AppendSelectedTravellers appends value to the "selected_travellers" field.
func (_u *GameUpdate) AppendSelectedTravellers(v []string) *GameUpdate {
	_u.mutation.AppendSelectedTravellers(v)
	return _u
}

// SetState sets the "state" field.
func (_u *GameUpdate) SetState(v game.State) *GameUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *GameUpdate) SetNillableState(v *game.State) *GameUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetScript sets the "script" edge to the Script entity.
func (_u *GameUpdate) SetScript(v *Script) *GameUpdate {
	return _u.SetScriptID(v.ID)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// ClearScript clears the "script" edge to the Script entity.
func (_u *GameUpdate) ClearScript() *GameUpdate {
	_u.mutation.ClearScript()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdate) check() error {
	if v, ok := _u.mutation.PlayerCount(); ok {
		if err := game.PlayerCountValidator(v); err != nil {
			return &ValidationError{Name: "player_count", err: fmt.Errorf(`ent: validator failed for field "Game.player_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TravellerCount(); ok {
		if err := game.TravellerCountValidator(v); err != nil {
			return &ValidationError{Name: "traveller_count", err: fmt.Errorf(`ent: validator failed for field "Game.traveller_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := game.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Game.state": %w`, err)}
		}
	}
	if _u.mutation.ScriptCleared() && len(_u.mutation.ScriptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Game.script"`)
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PlayerCount(); ok {
		_spec.SetField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerCount(); ok {
		_spec.AddField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TravellerCount(); ok {
		_spec.SetField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTravellerCount(); ok {
		_spec.AddField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SelectedRoles(); ok {
		_spec.SetField(game.FieldSelectedRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedRoles, value)
		})
	}
	if value, ok := _u.mutation.SelectedTravellers(); ok {
		_spec.SetField(game.FieldSelectedTravellers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedTravellers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedTravellers, value)
		})
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(game.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.ScriptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdateOne) SetUpdatedAt(v time.Time) *GameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *GameUpdateOne) SetScriptID(v int) *GameUpdateOne {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableScriptID(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetPlayerCount sets the "player_count" field.
func (_u *GameUpdateOne) SetPlayerCount(v int) *GameUpdateOne {
	_u.mutation.ResetPlayerCount()
	_u.mutation.SetPlayerCount(v)
	return _u
}

// SetNillablePlayerCount sets the "player_count" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillablePlayerCount(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetPlayerCount(*v)
	}
	return _u
}

// AddPlayerCount adds value to the "player_count" field.
func (_u *GameUpdateOne) AddPlayerCount(v int) *GameUpdateOne {
	_u.mutation.AddPlayerCount(v)
	return _u
}

// SetTravellerCount sets the "traveller_count" field.
func (_u *GameUpdateOne) SetTravellerCount(v int) *GameUpdateOne {
	_u.mutation.ResetTravellerCount()
	_u.mutation.SetTravellerCount(v)
	return _u
}

// SetNillableTravellerCount sets the "traveller_count" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableTravellerCount(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetTravellerCount(*v)
	}
	return _u
}

// AddTravellerCount adds value to the "traveller_count" field.
func (_u *GameUpdateOne) AddTravellerCount(v int) *GameUpdateOne {
	_u.mutation.AddTravellerCount(v)
	return _u
}

// SetSelectedRoles sets the "selected_roles" field.
func (_u *GameUpdateOne) SetSelectedRoles(v []string) *GameUpdateOne {
	_u.mutation.SetSelectedRoles(v)
	return _u
}

// AppendSelectedRoles appends value to the "selected_roles" field.
func (_u *GameUpdateOne) AppendSelectedRoles(v []string) *GameUpdateOne {
	_u.mutation.AppendSelectedRoles(v)
	return _u
}

// SetSelectedTravellers sets the "selected_travellers" field.
func (_u *GameUpdateOne) SetSelectedTravellers(v []string) *GameUpdateOne {
	_u.mutation.SetSelectedTravellers(v)
	return _u
}

// AppendSelectedTravellers appends value to the "selected_travellers" field.
func (_u *GameUpdateOne) AppendSelectedTravellers(v []string) *GameUpdateOne {
	_u.mutation.AppendSelectedTravellers(v)
	return _u
}

// SetState sets the "state" field.
func (_u *GameUpdateOne) SetState(v game.State) *GameUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableState(v *game.State) *GameUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetScript sets the "script" edge to the Script entity.
func (_u *GameUpdateOne) SetScript(v *Script) *GameUpdateOne {
	return _u.SetScriptID(v.ID)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// ClearScript clears the "script" edge to the Script entity.
func (_u *GameUpdateOne) ClearScript() *GameUpdateOne {
	_u.mutation.ClearScript()
	return _u
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdateOne) check() error {
	if v, ok := _u.mutation.PlayerCount(); ok {
		if err := game.PlayerCountValidator(v); err != nil {
			return &ValidationError{Name: "player_count", err: fmt.Errorf(`ent: validator failed for field "Game.player_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TravellerCount(); ok {
		if err := game.TravellerCountValidator(v); err != nil {
			return &ValidationError{Name: "traveller_count", err: fmt.Errorf(`ent: validator failed for field "Game.traveller_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := game.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Game.state": %w`, err)}
		}
	}
	if _u.mutation.ScriptCleared() && len(_u.mutation.ScriptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Game.script"`)
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PlayerCount(); ok {
		_spec.SetField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerCount(); ok {
		_spec.AddField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TravellerCount(); ok {
		_spec.SetField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTravellerCount(); ok {
		_spec.AddField(game.FieldTravellerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SelectedRoles(); ok {
		_spec.SetField(game.FieldSelectedRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedRoles, value)
		})
	}
	if value, ok := _u.mutation.SelectedTravellers(); ok {
		_spec.SetField(game.FieldSelectedTravellers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSelectedTravellers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldSelectedTravellers, value)
		})
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(game.FieldState, field.TypeEnum, value)
	}
	if _u.mutation.ScriptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.ScriptTable,
			Columns: []string{game.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
