// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shifty11/clockkeeper/ent/game"
	"github.com/shifty11/clockkeeper/ent/schema"
	"github.com/shifty11/clockkeeper/ent/script"
	"github.com/shifty11/clockkeeper/ent/user"
)

// Game is the model entity for the Game schema.
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ScriptID holds the value of the "script_id" field.
	ScriptID int `json:"script_id,omitempty"`
	// PlayerCount holds the value of the "player_count" field.
	PlayerCount int `json:"player_count,omitempty"`
	// TravellerCount holds the value of the "traveller_count" field.
	TravellerCount int `json:"traveller_count,omitempty"`
	// SelectedRoles holds the value of the "selected_roles" field.
	SelectedRoles []string `json:"selected_roles,omitempty"`
	// SelectedTravellers holds the value of the "selected_travellers" field.
	SelectedTravellers []string `json:"selected_travellers,omitempty"`
	// ExtraCharacters holds the value of the "extra_characters" field.
	ExtraCharacters []string `json:"extra_characters,omitempty"`
	// SelectedBluffs holds the value of the "selected_bluffs" field.
	SelectedBluffs []string `json:"selected_bluffs,omitempty"`
	// TravellerAlignments holds the value of the "traveller_alignments" field.
	TravellerAlignments map[string]schema.TravellerAlignment `json:"traveller_alignments,omitempty"`
	// GrimoirePositions holds the value of the "grimoire_positions" field.
	GrimoirePositions map[string]schema.GrimoirePosition `json:"grimoire_positions,omitempty"`
	// GrimoirePlayerNames holds the value of the "grimoire_player_names" field.
	GrimoirePlayerNames map[string]string `json:"grimoire_player_names,omitempty"`
	// GrimoireGameNotes holds the value of the "grimoire_game_notes" field.
	GrimoireGameNotes map[string]string `json:"grimoire_game_notes,omitempty"`
	// GrimoireRoundNotes holds the value of the "grimoire_round_notes" field.
	GrimoireRoundNotes map[string]string `json:"grimoire_round_notes,omitempty"`
	// BagSubstitutions holds the value of the "bag_substitutions" field.
	BagSubstitutions []schema.GameBagSubstitution `json:"bag_substitutions,omitempty"`
	// GrimoireReminderAttachments holds the value of the "grimoire_reminder_attachments" field.
	GrimoireReminderAttachments map[string]string `json:"grimoire_reminder_attachments,omitempty"`
	// State holds the value of the "state" field.
	State game.State `json:"state,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameQuery when eager-loading is set.
	Edges        GameEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GameEdges holds the relations/edges for other nodes in the graph.
type GameEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Script holds the value of the script edge.
	Script *Script `json:"script,omitempty"`
	// Phases holds the value of the phases edge.
	Phases []*Phase `json:"phases,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// ScriptOrErr returns the Script value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEdges) ScriptOrErr() (*Script, error) {
	if e.Script != nil {
		return e.Script, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: script.Label}
	}
	return nil, &NotLoadedError{edge: "script"}
}

// PhasesOrErr returns the Phases value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) PhasesOrErr() ([]*Phase, error) {
	if e.loadedTypes[2] {
		return e.Phases, nil
	}
	return nil, &NotLoadedError{edge: "phases"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldSelectedRoles, game.FieldSelectedTravellers, game.FieldExtraCharacters, game.FieldSelectedBluffs, game.FieldTravellerAlignments, game.FieldGrimoirePositions, game.FieldGrimoirePlayerNames, game.FieldGrimoireGameNotes, game.FieldGrimoireRoundNotes, game.FieldBagSubstitutions, game.FieldGrimoireReminderAttachments:
			values[i] = new([]byte)
		case game.FieldID, game.FieldUserID, game.FieldScriptID, game.FieldPlayerCount, game.FieldTravellerCount:
			values[i] = new(sql.NullInt64)
		case game.FieldName, game.FieldState:
			values[i] = new(sql.NullString)
		case game.FieldCreatedAt, game.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (_m *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case game.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case game.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case game.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case game.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case game.FieldScriptID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field script_id", values[i])
			} else if value.Valid {
				_m.ScriptID = int(value.Int64)
			}
		case game.FieldPlayerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field player_count", values[i])
			} else if value.Valid {
				_m.PlayerCount = int(value.Int64)
			}
		case game.FieldTravellerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field traveller_count", values[i])
			} else if value.Valid {
				_m.TravellerCount = int(value.Int64)
			}
		case game.FieldSelectedRoles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selected_roles", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectedRoles); err != nil {
					return fmt.Errorf("unmarshal field selected_roles: %w", err)
				}
			}
		case game.FieldSelectedTravellers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selected_travellers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectedTravellers); err != nil {
					return fmt.Errorf("unmarshal field selected_travellers: %w", err)
				}
			}
		case game.FieldExtraCharacters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_characters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraCharacters); err != nil {
					return fmt.Errorf("unmarshal field extra_characters: %w", err)
				}
			}
		case game.FieldSelectedBluffs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selected_bluffs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectedBluffs); err != nil {
					return fmt.Errorf("unmarshal field selected_bluffs: %w", err)
				}
			}
		case game.FieldTravellerAlignments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field traveller_alignments", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TravellerAlignments); err != nil {
					return fmt.Errorf("unmarshal field traveller_alignments: %w", err)
				}
			}
		case game.FieldGrimoirePositions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field grimoire_positions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GrimoirePositions); err != nil {
					return fmt.Errorf("unmarshal field grimoire_positions: %w", err)
				}
			}
		case game.FieldGrimoirePlayerNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field grimoire_player_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GrimoirePlayerNames); err != nil {
					return fmt.Errorf("unmarshal field grimoire_player_names: %w", err)
				}
			}
		case game.FieldGrimoireGameNotes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field grimoire_game_notes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GrimoireGameNotes); err != nil {
					return fmt.Errorf("unmarshal field grimoire_game_notes: %w", err)
				}
			}
		case game.FieldGrimoireRoundNotes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field grimoire_round_notes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GrimoireRoundNotes); err != nil {
					return fmt.Errorf("unmarshal field grimoire_round_notes: %w", err)
				}
			}
		case game.FieldBagSubstitutions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bag_substitutions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BagSubstitutions); err != nil {
					return fmt.Errorf("unmarshal field bag_substitutions: %w", err)
				}
			}
		case game.FieldGrimoireReminderAttachments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field grimoire_reminder_attachments", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GrimoireReminderAttachments); err != nil {
					return fmt.Errorf("unmarshal field grimoire_reminder_attachments: %w", err)
				}
			}
		case game.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = game.State(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (_m *Game) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Game entity.
func (_m *Game) QueryOwner() *UserQuery {
	return NewGameClient(_m.config).QueryOwner(_m)
}

// QueryScript queries the "script" edge of the Game entity.
func (_m *Game) QueryScript() *ScriptQuery {
	return NewGameClient(_m.config).QueryScript(_m)
}

// QueryPhases queries the "phases" edge of the Game entity.
func (_m *Game) QueryPhases() *PhaseQuery {
	return NewGameClient(_m.config).QueryPhases(_m)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Game) Update() *GameUpdateOne {
	return NewGameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Game) Unwrap() *Game {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Game is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("script_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScriptID))
	builder.WriteString(", ")
	builder.WriteString("player_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlayerCount))
	builder.WriteString(", ")
	builder.WriteString("traveller_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TravellerCount))
	builder.WriteString(", ")
	builder.WriteString("selected_roles=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedRoles))
	builder.WriteString(", ")
	builder.WriteString("selected_travellers=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedTravellers))
	builder.WriteString(", ")
	builder.WriteString("extra_characters=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraCharacters))
	builder.WriteString(", ")
	builder.WriteString("selected_bluffs=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedBluffs))
	builder.WriteString(", ")
	builder.WriteString("traveller_alignments=")
	builder.WriteString(fmt.Sprintf("%v", _m.TravellerAlignments))
	builder.WriteString(", ")
	builder.WriteString("grimoire_positions=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrimoirePositions))
	builder.WriteString(", ")
	builder.WriteString("grimoire_player_names=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrimoirePlayerNames))
	builder.WriteString(", ")
	builder.WriteString("grimoire_game_notes=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrimoireGameNotes))
	builder.WriteString(", ")
	builder.WriteString("grimoire_round_notes=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrimoireRoundNotes))
	builder.WriteString(", ")
	builder.WriteString("bag_substitutions=")
	builder.WriteString(fmt.Sprintf("%v", _m.BagSubstitutions))
	builder.WriteString(", ")
	builder.WriteString("grimoire_reminder_attachments=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrimoireReminderAttachments))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteByte(')')
	return builder.String()
}

// Games is a parsable slice of Game.
type Games []*Game
