// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/loomi-labs/clockkeeper/ent/game"
	"github.com/loomi-labs/clockkeeper/ent/script"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// Game is the model entity for the Game schema.
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ScriptID holds the value of the "script_id" field.
	ScriptID int `json:"script_id,omitempty"`
	// PlayerCount holds the value of the "player_count" field.
	PlayerCount int `json:"player_count,omitempty"`
	// TravellerCount holds the value of the "traveller_count" field.
	TravellerCount int `json:"traveller_count,omitempty"`
	// SelectedRoles holds the value of the "selected_roles" field.
	SelectedRoles []string `json:"selected_roles,omitempty"`
	// SelectedTravellers holds the value of the "selected_travellers" field.
	SelectedTravellers []string `json:"selected_travellers,omitempty"`
	// State holds the value of the "state" field.
	State game.State `json:"state,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameQuery when eager-loading is set.
	Edges        GameEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GameEdges holds the relations/edges for other nodes in the graph.
type GameEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Script holds the value of the script edge.
	Script *Script `json:"script,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// ScriptOrErr returns the Script value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEdges) ScriptOrErr() (*Script, error) {
	if e.Script != nil {
		return e.Script, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: script.Label}
	}
	return nil, &NotLoadedError{edge: "script"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldSelectedRoles, game.FieldSelectedTravellers:
			values[i] = new([]byte)
		case game.FieldID, game.FieldUserID, game.FieldScriptID, game.FieldPlayerCount, game.FieldTravellerCount:
			values[i] = new(sql.NullInt64)
		case game.FieldState:
			values[i] = new(sql.NullString)
		case game.FieldCreatedAt, game.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (_m *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case game.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case game.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case game.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case game.FieldScriptID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field script_id", values[i])
			} else if value.Valid {
				_m.ScriptID = int(value.Int64)
			}
		case game.FieldPlayerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field player_count", values[i])
			} else if value.Valid {
				_m.PlayerCount = int(value.Int64)
			}
		case game.FieldTravellerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field traveller_count", values[i])
			} else if value.Valid {
				_m.TravellerCount = int(value.Int64)
			}
		case game.FieldSelectedRoles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selected_roles", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectedRoles); err != nil {
					return fmt.Errorf("unmarshal field selected_roles: %w", err)
				}
			}
		case game.FieldSelectedTravellers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selected_travellers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectedTravellers); err != nil {
					return fmt.Errorf("unmarshal field selected_travellers: %w", err)
				}
			}
		case game.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = game.State(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (_m *Game) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Game entity.
func (_m *Game) QueryOwner() *UserQuery {
	return NewGameClient(_m.config).QueryOwner(_m)
}

// QueryScript queries the "script" edge of the Game entity.
func (_m *Game) QueryScript() *ScriptQuery {
	return NewGameClient(_m.config).QueryScript(_m)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Game) Update() *GameUpdateOne {
	return NewGameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Game) Unwrap() *Game {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Game is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("script_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScriptID))
	builder.WriteString(", ")
	builder.WriteString("player_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlayerCount))
	builder.WriteString(", ")
	builder.WriteString("traveller_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TravellerCount))
	builder.WriteString(", ")
	builder.WriteString("selected_roles=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedRoles))
	builder.WriteString(", ")
	builder.WriteString("selected_travellers=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedTravellers))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteByte(')')
	return builder.String()
}

// Games is a parsable slice of Game.
type Games []*Game
