// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/clockkeeper/ent/death"
	"github.com/shifty11/clockkeeper/ent/game"
	"github.com/shifty11/clockkeeper/ent/phase"
	"github.com/shifty11/clockkeeper/ent/predicate"
)

// PhaseUpdate is the builder for updating Phase entities.
type PhaseUpdate struct {
	config
	hooks    []Hook
	mutation *PhaseMutation
}

// Where appends a list predicates to the PhaseUpdate builder.
func (_u *PhaseUpdate) Where(ps ...predicate.Phase) *PhaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PhaseUpdate) SetUpdatedAt(v time.Time) *PhaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *PhaseUpdate) SetGameID(v int) *PhaseUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *PhaseUpdate) SetNillableGameID(v *int) *PhaseUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRoundNumber sets the "round_number" field.
func (_u *PhaseUpdate) SetRoundNumber(v int) *PhaseUpdate {
	_u.mutation.ResetRoundNumber()
	_u.mutation.SetRoundNumber(v)
	return _u
}

// SetNillableRoundNumber sets the "round_number" field if the given value is not nil.
func (_u *PhaseUpdate) SetNillableRoundNumber(v *int) *PhaseUpdate {
	if v != nil {
		_u.SetRoundNumber(*v)
	}
	return _u
}

// AddRoundNumber adds value to the "round_number" field.
func (_u *PhaseUpdate) AddRoundNumber(v int) *PhaseUpdate {
	_u.mutation.AddRoundNumber(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PhaseUpdate) SetType(v phase.Type) *PhaseUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PhaseUpdate) SetNillableType(v *phase.Type) *PhaseUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PhaseUpdate) SetIsActive(v bool) *PhaseUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PhaseUpdate) SetNillableIsActive(v *bool) *PhaseUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCompletedActions sets the "completed_actions" field.
func (_u *PhaseUpdate) SetCompletedActions(v []string) *PhaseUpdate {
	_u.mutation.SetCompletedActions(v)
	return _u
}

// AppendCompletedActions appends value to the "completed_actions" field.
func (_u *PhaseUpdate) AppendCompletedActions(v []string) *PhaseUpdate {
	_u.mutation.AppendCompletedActions(v)
	return _u
}

// ClearCompletedActions clears the value of the "completed_actions" field.
func (_u *PhaseUpdate) ClearCompletedActions() *PhaseUpdate {
	_u.mutation.ClearCompletedActions()
	return _u
}

// SetCharacterAlignments sets the "character_alignments" field.
func (_u *PhaseUpdate) SetCharacterAlignments(v map[string]string) *PhaseUpdate {
	_u.mutation.SetCharacterAlignments(v)
	return _u
}

// ClearCharacterAlignments clears the value of the "character_alignments" field.
func (_u *PhaseUpdate) ClearCharacterAlignments() *PhaseUpdate {
	_u.mutation.ClearCharacterAlignments()
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *PhaseUpdate) SetGame(v *Game) *PhaseUpdate {
	return _u.SetGameID(v.ID)
}

// AddDeathIDs adds the "deaths" edge to the Death entity by IDs.
func (_u *PhaseUpdate) AddDeathIDs(ids ...int) *PhaseUpdate {
	_u.mutation.AddDeathIDs(ids...)
	return _u
}

// AddDeaths adds the "deaths" edges to the Death entity.
func (_u *PhaseUpdate) AddDeaths(v ...*Death) *PhaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeathIDs(ids...)
}

// Mutation returns the PhaseMutation object of the builder.
func (_u *PhaseUpdate) Mutation() *PhaseMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *PhaseUpdate) ClearGame() *PhaseUpdate {
	_u.mutation.ClearGame()
	return _u
}

// ClearDeaths clears all "deaths" edges to the Death entity.
func (_u *PhaseUpdate) ClearDeaths() *PhaseUpdate {
	_u.mutation.ClearDeaths()
	return _u
}

// RemoveDeathIDs removes the "deaths" edge to Death entities by IDs.
func (_u *PhaseUpdate) RemoveDeathIDs(ids ...int) *PhaseUpdate {
	_u.mutation.RemoveDeathIDs(ids...)
	return _u
}

// RemoveDeaths removes "deaths" edges to Death entities.
func (_u *PhaseUpdate) RemoveDeaths(v ...*Death) *PhaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeathIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PhaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PhaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PhaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PhaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PhaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := phase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PhaseUpdate) check() error {
	if v, ok := _u.mutation.RoundNumber(); ok {
		if err := phase.RoundNumberValidator(v); err != nil {
			return &ValidationError{Name: "round_number", err: fmt.Errorf(`ent: validator failed for field "Phase.round_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := phase.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Phase.type": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Phase.game"`)
	}
	return nil
}

func (_u *PhaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(phase.Table, phase.Columns, sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(phase.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoundNumber(); ok {
		_spec.SetField(phase.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundNumber(); ok {
		_spec.AddField(phase.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(phase.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(phase.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompletedActions(); ok {
		_spec.SetField(phase.FieldCompletedActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCompletedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, phase.FieldCompletedActions, value)
		})
	}
	if _u.mutation.CompletedActionsCleared() {
		_spec.ClearField(phase.FieldCompletedActions, field.TypeJSON)
	}
	if value, ok := _u.mutation.CharacterAlignments(); ok {
		_spec.SetField(phase.FieldCharacterAlignments, field.TypeJSON, value)
	}
	if _u.mutation.CharacterAlignmentsCleared() {
		_spec.ClearField(phase.FieldCharacterAlignments, field.TypeJSON)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   phase.GameTable,
			Columns: []string{phase.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   phase.GameTable,
			Columns: []string{phase.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeathsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.DeathsTable,
			Columns: []string{phase.DeathsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeathsIDs(); len(nodes) > 0 && !_u.mutation.DeathsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.DeathsTable,
			Columns: []string{phase.DeathsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeathsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.DeathsTable,
			Columns: []string{phase.DeathsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{phase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PhaseUpdateOne is the builder for updating a single Phase entity.
type PhaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PhaseMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PhaseUpdateOne) SetUpdatedAt(v time.Time) *PhaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *PhaseUpdateOne) SetGameID(v int) *PhaseUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *PhaseUpdateOne) SetNillableGameID(v *int) *PhaseUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRoundNumber sets the "round_number" field.
func (_u *PhaseUpdateOne) SetRoundNumber(v int) *PhaseUpdateOne {
	_u.mutation.ResetRoundNumber()
	_u.mutation.SetRoundNumber(v)
	return _u
}

// SetNillableRoundNumber sets the "round_number" field if the given value is not nil.
func (_u *PhaseUpdateOne) SetNillableRoundNumber(v *int) *PhaseUpdateOne {
	if v != nil {
		_u.SetRoundNumber(*v)
	}
	return _u
}

// AddRoundNumber adds value to the "round_number" field.
func (_u *PhaseUpdateOne) AddRoundNumber(v int) *PhaseUpdateOne {
	_u.mutation.AddRoundNumber(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PhaseUpdateOne) SetType(v phase.Type) *PhaseUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PhaseUpdateOne) SetNillableType(v *phase.Type) *PhaseUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PhaseUpdateOne) SetIsActive(v bool) *PhaseUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PhaseUpdateOne) SetNillableIsActive(v *bool) *PhaseUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCompletedActions sets the "completed_actions" field.
func (_u *PhaseUpdateOne) SetCompletedActions(v []string) *PhaseUpdateOne {
	_u.mutation.SetCompletedActions(v)
	return _u
}

// AppendCompletedActions appends value to the "completed_actions" field.
func (_u *PhaseUpdateOne) AppendCompletedActions(v []string) *PhaseUpdateOne {
	_u.mutation.AppendCompletedActions(v)
	return _u
}

// ClearCompletedActions clears the value of the "completed_actions" field.
func (_u *PhaseUpdateOne) ClearCompletedActions() *PhaseUpdateOne {
	_u.mutation.ClearCompletedActions()
	return _u
}

// SetCharacterAlignments sets the "character_alignments" field.
func (_u *PhaseUpdateOne) SetCharacterAlignments(v map[string]string) *PhaseUpdateOne {
	_u.mutation.SetCharacterAlignments(v)
	return _u
}

// ClearCharacterAlignments clears the value of the "character_alignments" field.
func (_u *PhaseUpdateOne) ClearCharacterAlignments() *PhaseUpdateOne {
	_u.mutation.ClearCharacterAlignments()
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *PhaseUpdateOne) SetGame(v *Game) *PhaseUpdateOne {
	return _u.SetGameID(v.ID)
}

// AddDeathIDs adds the "deaths" edge to the Death entity by IDs.
func (_u *PhaseUpdateOne) AddDeathIDs(ids ...int) *PhaseUpdateOne {
	_u.mutation.AddDeathIDs(ids...)
	return _u
}

// AddDeaths adds the "deaths" edges to the Death entity.
func (_u *PhaseUpdateOne) AddDeaths(v ...*Death) *PhaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeathIDs(ids...)
}

// Mutation returns the PhaseMutation object of the builder.
func (_u *PhaseUpdateOne) Mutation() *PhaseMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *PhaseUpdateOne) ClearGame() *PhaseUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// ClearDeaths clears all "deaths" edges to the Death entity.
func (_u *PhaseUpdateOne) ClearDeaths() *PhaseUpdateOne {
	_u.mutation.ClearDeaths()
	return _u
}

// RemoveDeathIDs removes the "deaths" edge to Death entities by IDs.
func (_u *PhaseUpdateOne) RemoveDeathIDs(ids ...int) *PhaseUpdateOne {
	_u.mutation.RemoveDeathIDs(ids...)
	return _u
}

// RemoveDeaths removes "deaths" edges to Death entities.
func (_u *PhaseUpdateOne) RemoveDeaths(v ...*Death) *PhaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeathIDs(ids...)
}

// Where appends a list predicates to the PhaseUpdate builder.
func (_u *PhaseUpdateOne) Where(ps ...predicate.Phase) *PhaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PhaseUpdateOne) Select(field string, fields ...string) *PhaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Phase entity.
func (_u *PhaseUpdateOne) Save(ctx context.Context) (*Phase, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PhaseUpdateOne) SaveX(ctx context.Context) *Phase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PhaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PhaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PhaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := phase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PhaseUpdateOne) check() error {
	if v, ok := _u.mutation.RoundNumber(); ok {
		if err := phase.RoundNumberValidator(v); err != nil {
			return &ValidationError{Name: "round_number", err: fmt.Errorf(`ent: validator failed for field "Phase.round_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := phase.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Phase.type": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Phase.game"`)
	}
	return nil
}

func (_u *PhaseUpdateOne) sqlSave(ctx context.Context) (_node *Phase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(phase.Table, phase.Columns, sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Phase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, phase.FieldID)
		for _, f := range fields {
			if !phase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != phase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(phase.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoundNumber(); ok {
		_spec.SetField(phase.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundNumber(); ok {
		_spec.AddField(phase.FieldRoundNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(phase.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(phase.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompletedActions(); ok {
		_spec.SetField(phase.FieldCompletedActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCompletedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, phase.FieldCompletedActions, value)
		})
	}
	if _u.mutation.CompletedActionsCleared() {
		_spec.ClearField(phase.FieldCompletedActions, field.TypeJSON)
	}
	if value, ok := _u.mutation.CharacterAlignments(); ok {
		_spec.SetField(phase.FieldCharacterAlignments, field.TypeJSON, value)
	}
	if _u.mutation.CharacterAlignmentsCleared() {
		_spec.ClearField(phase.FieldCharacterAlignments, field.TypeJSON)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   phase.GameTable,
			Columns: []string{phase.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   phase.GameTable,
			Columns: []string{phase.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeathsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.DeathsTable,
			Columns: []string{phase.DeathsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeathsIDs(); len(nodes) > 0 && !_u.mutation.DeathsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.DeathsTable,
			Columns: []string{phase.DeathsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeathsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.DeathsTable,
			Columns: []string{phase.DeathsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Phase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{phase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
