// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shifty11/clockkeeper/ent/game"
	"github.com/shifty11/clockkeeper/ent/phase"
)

// Phase is the model entity for the Phase schema.
type Phase struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID int `json:"game_id,omitempty"`
	// RoundNumber holds the value of the "round_number" field.
	RoundNumber int `json:"round_number,omitempty"`
	// Type holds the value of the "type" field.
	Type phase.Type `json:"type,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CompletedActions holds the value of the "completed_actions" field.
	CompletedActions []string `json:"completed_actions,omitempty"`
	// CharacterAlignments holds the value of the "character_alignments" field.
	CharacterAlignments map[string]string `json:"character_alignments,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PhaseQuery when eager-loading is set.
	Edges        PhaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PhaseEdges holds the relations/edges for other nodes in the graph.
type PhaseEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// Deaths holds the value of the deaths edge.
	Deaths []*Death `json:"deaths,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhaseEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// DeathsOrErr returns the Deaths value or an error if the edge
// was not loaded in eager-loading.
func (e PhaseEdges) DeathsOrErr() ([]*Death, error) {
	if e.loadedTypes[1] {
		return e.Deaths, nil
	}
	return nil, &NotLoadedError{edge: "deaths"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Phase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case phase.FieldCompletedActions, phase.FieldCharacterAlignments:
			values[i] = new([]byte)
		case phase.FieldIsActive:
			values[i] = new(sql.NullBool)
		case phase.FieldID, phase.FieldGameID, phase.FieldRoundNumber:
			values[i] = new(sql.NullInt64)
		case phase.FieldType:
			values[i] = new(sql.NullString)
		case phase.FieldCreatedAt, phase.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Phase fields.
func (_m *Phase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case phase.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case phase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case phase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case phase.FieldGameID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = int(value.Int64)
			}
		case phase.FieldRoundNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field round_number", values[i])
			} else if value.Valid {
				_m.RoundNumber = int(value.Int64)
			}
		case phase.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = phase.Type(value.String)
			}
		case phase.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case phase.FieldCompletedActions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field completed_actions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CompletedActions); err != nil {
					return fmt.Errorf("unmarshal field completed_actions: %w", err)
				}
			}
		case phase.FieldCharacterAlignments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field character_alignments", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CharacterAlignments); err != nil {
					return fmt.Errorf("unmarshal field character_alignments: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Phase.
// This includes values selected through modifiers, order, etc.
func (_m *Phase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the Phase entity.
func (_m *Phase) QueryGame() *GameQuery {
	return NewPhaseClient(_m.config).QueryGame(_m)
}

// QueryDeaths queries the "deaths" edge of the Phase entity.
func (_m *Phase) QueryDeaths() *DeathQuery {
	return NewPhaseClient(_m.config).QueryDeaths(_m)
}

// Update returns a builder for updating this Phase.
// Note that you need to call Phase.Unwrap() before calling this method if this Phase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Phase) Update() *PhaseUpdateOne {
	return NewPhaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Phase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Phase) Unwrap() *Phase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Phase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Phase) String() string {
	var builder strings.Builder
	builder.WriteString("Phase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("game_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GameID))
	builder.WriteString(", ")
	builder.WriteString("round_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoundNumber))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("completed_actions=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedActions))
	builder.WriteString(", ")
	builder.WriteString("character_alignments=")
	builder.WriteString(fmt.Sprintf("%v", _m.CharacterAlignments))
	builder.WriteByte(')')
	return builder.String()
}

// Phases is a parsable slice of Phase.
type Phases []*Phase
