// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/clockkeeper/ent/death"
	"github.com/shifty11/clockkeeper/ent/game"
	"github.com/shifty11/clockkeeper/ent/phase"
)

// PhaseCreate is the builder for creating a Phase entity.
type PhaseCreate struct {
	config
	mutation *PhaseMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PhaseCreate) SetCreatedAt(v time.Time) *PhaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PhaseCreate) SetNillableCreatedAt(v *time.Time) *PhaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PhaseCreate) SetUpdatedAt(v time.Time) *PhaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PhaseCreate) SetNillableUpdatedAt(v *time.Time) *PhaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGameID sets the "game_id" field.
func (_c *PhaseCreate) SetGameID(v int) *PhaseCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetRoundNumber sets the "round_number" field.
func (_c *PhaseCreate) SetRoundNumber(v int) *PhaseCreate {
	_c.mutation.SetRoundNumber(v)
	return _c
}

// SetType sets the "type" field.
func (_c *PhaseCreate) SetType(v phase.Type) *PhaseCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *PhaseCreate) SetIsActive(v bool) *PhaseCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *PhaseCreate) SetNillableIsActive(v *bool) *PhaseCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCompletedActions sets the "completed_actions" field.
func (_c *PhaseCreate) SetCompletedActions(v []string) *PhaseCreate {
	_c.mutation.SetCompletedActions(v)
	return _c
}

// SetCharacterAlignments sets the "character_alignments" field.
func (_c *PhaseCreate) SetCharacterAlignments(v map[string]string) *PhaseCreate {
	_c.mutation.SetCharacterAlignments(v)
	return _c
}

// SetGame sets the "game" edge to the Game entity.
func (_c *PhaseCreate) SetGame(v *Game) *PhaseCreate {
	return _c.SetGameID(v.ID)
}

// AddDeathIDs adds the "deaths" edge to the Death entity by IDs.
func (_c *PhaseCreate) AddDeathIDs(ids ...int) *PhaseCreate {
	_c.mutation.AddDeathIDs(ids...)
	return _c
}

// AddDeaths adds the "deaths" edges to the Death entity.
func (_c *PhaseCreate) AddDeaths(v ...*Death) *PhaseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeathIDs(ids...)
}

// Mutation returns the PhaseMutation object of the builder.
func (_c *PhaseCreate) Mutation() *PhaseMutation {
	return _c.mutation
}

// Save creates the Phase in the database.
func (_c *PhaseCreate) Save(ctx context.Context) (*Phase, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PhaseCreate) SaveX(ctx context.Context) *Phase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PhaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := phase.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := phase.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := phase.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CompletedActions(); !ok {
		v := phase.DefaultCompletedActions
		_c.mutation.SetCompletedActions(v)
	}
	if _, ok := _c.mutation.CharacterAlignments(); !ok {
		v := phase.DefaultCharacterAlignments
		_c.mutation.SetCharacterAlignments(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PhaseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Phase.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Phase.updated_at"`)}
	}
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`ent: missing required field "Phase.game_id"`)}
	}
	if _, ok := _c.mutation.RoundNumber(); !ok {
		return &ValidationError{Name: "round_number", err: errors.New(`ent: missing required field "Phase.round_number"`)}
	}
	if v, ok := _c.mutation.RoundNumber(); ok {
		if err := phase.RoundNumberValidator(v); err != nil {
			return &ValidationError{Name: "round_number", err: fmt.Errorf(`ent: validator failed for field "Phase.round_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Phase.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := phase.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Phase.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Phase.is_active"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "Phase.game"`)}
	}
	return nil
}

func (_c *PhaseCreate) sqlSave(ctx context.Context) (*Phase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PhaseCreate) createSpec() (*Phase, *sqlgraph.CreateSpec) {
	var (
		_node = &Phase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(phase.Table, sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(phase.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(phase.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RoundNumber(); ok {
		_spec.SetField(phase.FieldRoundNumber, field.TypeInt, value)
		_node.RoundNumber = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(phase.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(phase.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CompletedActions(); ok {
		_spec.SetField(phase.FieldCompletedActions, field.TypeJSON, value)
		_node.CompletedActions = value
	}
	if value, ok := _c.mutation.CharacterAlignments(); ok {
		_spec.SetField(phase.FieldCharacterAlignments, field.TypeJSON, value)
		_node.CharacterAlignments = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   phase.GameTable,
			Columns: []string{phase.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GameID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeathsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   phase.DeathsTable,
			Columns: []string{phase.DeathsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(death.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PhaseCreateBulk is the builder for creating many Phase entities in bulk.
type PhaseCreateBulk struct {
	config
	err      error
	builders []*PhaseCreate
}

// Save creates the Phase entities in the database.
func (_c *PhaseCreateBulk) Save(ctx context.Context) ([]*Phase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Phase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PhaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PhaseCreateBulk) SaveX(ctx context.Context) []*Phase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PhaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PhaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
