// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/shifty11/clockkeeper/ent/death"
	"github.com/shifty11/clockkeeper/ent/game"
	"github.com/shifty11/clockkeeper/ent/phase"
	"github.com/shifty11/clockkeeper/ent/schema"
	"github.com/shifty11/clockkeeper/ent/script"
	"github.com/shifty11/clockkeeper/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deathMixin := schema.Death{}.Mixin()
	deathMixinFields0 := deathMixin[0].Fields()
	_ = deathMixinFields0
	deathFields := schema.Death{}.Fields()
	_ = deathFields
	// deathDescCreatedAt is the schema descriptor for created_at field.
	deathDescCreatedAt := deathMixinFields0[0].Descriptor()
	// death.DefaultCreatedAt holds the default value on creation for the created_at field.
	death.DefaultCreatedAt = deathDescCreatedAt.Default.(func() time.Time)
	// deathDescUpdatedAt is the schema descriptor for updated_at field.
	deathDescUpdatedAt := deathMixinFields0[1].Descriptor()
	// death.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	death.DefaultUpdatedAt = deathDescUpdatedAt.Default.(func() time.Time)
	// death.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	death.UpdateDefaultUpdatedAt = deathDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deathDescRoleID is the schema descriptor for role_id field.
	deathDescRoleID := deathFields[1].Descriptor()
	// death.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	death.RoleIDValidator = deathDescRoleID.Validators[0].(func(string) error)
	// deathDescGhostVote is the schema descriptor for ghost_vote field.
	deathDescGhostVote := deathFields[2].Descriptor()
	// death.DefaultGhostVote holds the default value on creation for the ghost_vote field.
	death.DefaultGhostVote = deathDescGhostVote.Default.(bool)
	gameMixin := schema.Game{}.Mixin()
	gameMixinFields0 := gameMixin[0].Fields()
	_ = gameMixinFields0
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescCreatedAt is the schema descriptor for created_at field.
	gameDescCreatedAt := gameMixinFields0[0].Descriptor()
	// game.DefaultCreatedAt holds the default value on creation for the created_at field.
	game.DefaultCreatedAt = gameDescCreatedAt.Default.(func() time.Time)
	// gameDescUpdatedAt is the schema descriptor for updated_at field.
	gameDescUpdatedAt := gameMixinFields0[1].Descriptor()
	// game.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	game.DefaultUpdatedAt = gameDescUpdatedAt.Default.(func() time.Time)
	// game.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	game.UpdateDefaultUpdatedAt = gameDescUpdatedAt.UpdateDefault.(func() time.Time)
	// gameDescName is the schema descriptor for name field.
	gameDescName := gameFields[0].Descriptor()
	// game.DefaultName holds the default value on creation for the name field.
	game.DefaultName = gameDescName.Default.(string)
	// gameDescPlayerCount is the schema descriptor for player_count field.
	gameDescPlayerCount := gameFields[3].Descriptor()
	// game.PlayerCountValidator is a validator for the "player_count" field. It is called by the builders before save.
	game.PlayerCountValidator = func() func(int) error {
		validators := gameDescPlayerCount.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(player_count int) error {
			for _, fn := range fns {
				if err := fn(player_count); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gameDescTravellerCount is the schema descriptor for traveller_count field.
	gameDescTravellerCount := gameFields[4].Descriptor()
	// game.DefaultTravellerCount holds the default value on creation for the traveller_count field.
	game.DefaultTravellerCount = gameDescTravellerCount.Default.(int)
	// game.TravellerCountValidator is a validator for the "traveller_count" field. It is called by the builders before save.
	game.TravellerCountValidator = func() func(int) error {
		validators := gameDescTravellerCount.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(traveller_count int) error {
			for _, fn := range fns {
				if err := fn(traveller_count); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gameDescExtraCharacters is the schema descriptor for extra_characters field.
	gameDescExtraCharacters := gameFields[7].Descriptor()
	// game.DefaultExtraCharacters holds the default value on creation for the extra_characters field.
	game.DefaultExtraCharacters = gameDescExtraCharacters.Default.([]string)
	// gameDescSelectedBluffs is the schema descriptor for selected_bluffs field.
	gameDescSelectedBluffs := gameFields[8].Descriptor()
	// game.DefaultSelectedBluffs holds the default value on creation for the selected_bluffs field.
	game.DefaultSelectedBluffs = gameDescSelectedBluffs.Default.([]string)
	// gameDescTravellerAlignments is the schema descriptor for traveller_alignments field.
	gameDescTravellerAlignments := gameFields[9].Descriptor()
	// game.DefaultTravellerAlignments holds the default value on creation for the traveller_alignments field.
	game.DefaultTravellerAlignments = gameDescTravellerAlignments.Default.(map[string]schema.TravellerAlignment)
	// gameDescGrimoirePositions is the schema descriptor for grimoire_positions field.
	gameDescGrimoirePositions := gameFields[10].Descriptor()
	// game.DefaultGrimoirePositions holds the default value on creation for the grimoire_positions field.
	game.DefaultGrimoirePositions = gameDescGrimoirePositions.Default.(map[string]schema.GrimoirePosition)
	// gameDescGrimoirePlayerNames is the schema descriptor for grimoire_player_names field.
	gameDescGrimoirePlayerNames := gameFields[11].Descriptor()
	// game.DefaultGrimoirePlayerNames holds the default value on creation for the grimoire_player_names field.
	game.DefaultGrimoirePlayerNames = gameDescGrimoirePlayerNames.Default.(map[string]string)
	// gameDescGrimoireGameNotes is the schema descriptor for grimoire_game_notes field.
	gameDescGrimoireGameNotes := gameFields[12].Descriptor()
	// game.DefaultGrimoireGameNotes holds the default value on creation for the grimoire_game_notes field.
	game.DefaultGrimoireGameNotes = gameDescGrimoireGameNotes.Default.(map[string]string)
	// gameDescGrimoireRoundNotes is the schema descriptor for grimoire_round_notes field.
	gameDescGrimoireRoundNotes := gameFields[13].Descriptor()
	// game.DefaultGrimoireRoundNotes holds the default value on creation for the grimoire_round_notes field.
	game.DefaultGrimoireRoundNotes = gameDescGrimoireRoundNotes.Default.(map[string]string)
	// gameDescBagSubstitutions is the schema descriptor for bag_substitutions field.
	gameDescBagSubstitutions := gameFields[14].Descriptor()
	// game.DefaultBagSubstitutions holds the default value on creation for the bag_substitutions field.
	game.DefaultBagSubstitutions = gameDescBagSubstitutions.Default.([]schema.GameBagSubstitution)
	// gameDescGrimoireReminderAttachments is the schema descriptor for grimoire_reminder_attachments field.
	gameDescGrimoireReminderAttachments := gameFields[15].Descriptor()
	// game.DefaultGrimoireReminderAttachments holds the default value on creation for the grimoire_reminder_attachments field.
	game.DefaultGrimoireReminderAttachments = gameDescGrimoireReminderAttachments.Default.(map[string]string)
	phaseMixin := schema.Phase{}.Mixin()
	phaseMixinFields0 := phaseMixin[0].Fields()
	_ = phaseMixinFields0
	phaseFields := schema.Phase{}.Fields()
	_ = phaseFields
	// phaseDescCreatedAt is the schema descriptor for created_at field.
	phaseDescCreatedAt := phaseMixinFields0[0].Descriptor()
	// phase.DefaultCreatedAt holds the default value on creation for the created_at field.
	phase.DefaultCreatedAt = phaseDescCreatedAt.Default.(func() time.Time)
	// phaseDescUpdatedAt is the schema descriptor for updated_at field.
	phaseDescUpdatedAt := phaseMixinFields0[1].Descriptor()
	// phase.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	phase.DefaultUpdatedAt = phaseDescUpdatedAt.Default.(func() time.Time)
	// phase.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	phase.UpdateDefaultUpdatedAt = phaseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// phaseDescRoundNumber is the schema descriptor for round_number field.
	phaseDescRoundNumber := phaseFields[1].Descriptor()
	// phase.RoundNumberValidator is a validator for the "round_number" field. It is called by the builders before save.
	phase.RoundNumberValidator = phaseDescRoundNumber.Validators[0].(func(int) error)
	// phaseDescIsActive is the schema descriptor for is_active field.
	phaseDescIsActive := phaseFields[3].Descriptor()
	// phase.DefaultIsActive holds the default value on creation for the is_active field.
	phase.DefaultIsActive = phaseDescIsActive.Default.(bool)
	// phaseDescCompletedActions is the schema descriptor for completed_actions field.
	phaseDescCompletedActions := phaseFields[4].Descriptor()
	// phase.DefaultCompletedActions holds the default value on creation for the completed_actions field.
	phase.DefaultCompletedActions = phaseDescCompletedActions.Default.([]string)
	// phaseDescCharacterAlignments is the schema descriptor for character_alignments field.
	phaseDescCharacterAlignments := phaseFields[5].Descriptor()
	// phase.DefaultCharacterAlignments holds the default value on creation for the character_alignments field.
	phase.DefaultCharacterAlignments = phaseDescCharacterAlignments.Default.(map[string]string)
	scriptMixin := schema.Script{}.Mixin()
	scriptMixinFields0 := scriptMixin[0].Fields()
	_ = scriptMixinFields0
	scriptFields := schema.Script{}.Fields()
	_ = scriptFields
	// scriptDescCreatedAt is the schema descriptor for created_at field.
	scriptDescCreatedAt := scriptMixinFields0[0].Descriptor()
	// script.DefaultCreatedAt holds the default value on creation for the created_at field.
	script.DefaultCreatedAt = scriptDescCreatedAt.Default.(func() time.Time)
	// scriptDescUpdatedAt is the schema descriptor for updated_at field.
	scriptDescUpdatedAt := scriptMixinFields0[1].Descriptor()
	// script.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	script.DefaultUpdatedAt = scriptDescUpdatedAt.Default.(func() time.Time)
	// script.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	script.UpdateDefaultUpdatedAt = scriptDescUpdatedAt.UpdateDefault.(func() time.Time)
	// scriptDescName is the schema descriptor for name field.
	scriptDescName := scriptFields[0].Descriptor()
	// script.NameValidator is a validator for the "name" field. It is called by the builders before save.
	script.NameValidator = scriptDescName.Validators[0].(func(string) error)
	// scriptDescEdition is the schema descriptor for edition field.
	scriptDescEdition := scriptFields[1].Descriptor()
	// script.DefaultEdition holds the default value on creation for the edition field.
	script.DefaultEdition = scriptDescEdition.Default.(string)
	// scriptDescIsSystem is the schema descriptor for is_system field.
	scriptDescIsSystem := scriptFields[3].Descriptor()
	// script.DefaultIsSystem holds the default value on creation for the is_system field.
	script.DefaultIsSystem = scriptDescIsSystem.Default.(bool)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUUID is the schema descriptor for uuid field.
	userDescUUID := userFields[0].Descriptor()
	// user.DefaultUUID holds the default value on creation for the uuid field.
	user.DefaultUUID = userDescUUID.Default.(func() string)
	// user.UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	user.UUIDValidator = userDescUUID.Validators[0].(func(string) error)
	// userDescIsAnonymous is the schema descriptor for is_anonymous field.
	userDescIsAnonymous := userFields[4].Descriptor()
	// user.DefaultIsAnonymous holds the default value on creation for the is_anonymous field.
	user.DefaultIsAnonymous = userDescIsAnonymous.Default.(bool)
	// userDescLastActiveAt is the schema descriptor for last_active_at field.
	userDescLastActiveAt := userFields[5].Descriptor()
	// user.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	user.DefaultLastActiveAt = userDescLastActiveAt.Default.(func() time.Time)
	// userDescPlayerPresets is the schema descriptor for player_presets field.
	userDescPlayerPresets := userFields[6].Descriptor()
	// user.DefaultPlayerPresets holds the default value on creation for the player_presets field.
	user.DefaultPlayerPresets = userDescPlayerPresets.Default.([]string)
}
