// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/game"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
	"github.com/loomi-labs/clockkeeper/ent/script"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// ScriptUpdate is the builder for updating Script entities.
type ScriptUpdate struct {
	config
	hooks    []Hook
	mutation *ScriptMutation
}

// Where appends a list predicates to the ScriptUpdate builder.
func (_u *ScriptUpdate) Where(ps ...predicate.Script) *ScriptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptUpdate) SetUpdatedAt(v time.Time) *ScriptUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ScriptUpdate) SetName(v string) *ScriptUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableName(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEdition sets the "edition" field.
func (_u *ScriptUpdate) SetEdition(v string) *ScriptUpdate {
	_u.mutation.SetEdition(v)
	return _u
}

// SetNillableEdition sets the "edition" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableEdition(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetEdition(*v)
	}
	return _u
}

// SetCharacterIds sets the "character_ids" field.
func (_u *ScriptUpdate) SetCharacterIds(v []string) *ScriptUpdate {
	_u.mutation.SetCharacterIds(v)
	return _u
}

// AppendCharacterIds appends value to the "character_ids" field.
func (_u *ScriptUpdate) AppendCharacterIds(v []string) *ScriptUpdate {
	_u.mutation.AppendCharacterIds(v)
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *ScriptUpdate) SetIsSystem(v bool) *ScriptUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableIsSystem(v *bool) *ScriptUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ScriptUpdate) SetUserID(v int) *ScriptUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableUserID(v *int) *ScriptUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ScriptUpdate) ClearUserID() *ScriptUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ScriptUpdate) SetDeletedAt(v time.Time) *ScriptUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableDeletedAt(v *time.Time) *ScriptUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ScriptUpdate) ClearDeletedAt() *ScriptUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ScriptUpdate) SetOwnerID(id int) *ScriptUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ScriptUpdate) SetNillableOwnerID(id *int) *ScriptUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ScriptUpdate) SetOwner(v *User) *ScriptUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (_u *ScriptUpdate) AddGameIDs(ids ...int) *ScriptUpdate {
	_u.mutation.AddGameIDs(ids...)
	return _u
}

// AddGames adds the "games" edges to the Game entity.
func (_u *ScriptUpdate) AddGames(v ...*Game) *ScriptUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGameIDs(ids...)
}

// Mutation returns the ScriptMutation object of the builder.
func (_u *ScriptUpdate) Mutation() *ScriptMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ScriptUpdate) ClearOwner() *ScriptUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearGames clears all "games" edges to the Game entity.
func (_u *ScriptUpdate) ClearGames() *ScriptUpdate {
	_u.mutation.ClearGames()
	return _u
}

// RemoveGameIDs removes the "games" edge to Game entities by IDs.
func (_u *ScriptUpdate) RemoveGameIDs(ids ...int) *ScriptUpdate {
	_u.mutation.RemoveGameIDs(ids...)
	return _u
}

// RemoveGames removes "games" edges to Game entities.
func (_u *ScriptUpdate) RemoveGames(v ...*Game) *ScriptUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGameIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScriptUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScriptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := script.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ScriptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(script.Table, script.Columns, sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(script.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Edition(); ok {
		_spec.SetField(script.FieldEdition, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterIds(); ok {
		_spec.SetField(script.FieldCharacterIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCharacterIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, script.FieldCharacterIds, value)
		})
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(script.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(script.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(script.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   script.OwnerTable,
			Columns: []string{script.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   script.OwnerTable,
			Columns: []string{script.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.GamesTable,
			Columns: []string{script.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamesIDs(); len(nodes) > 0 && !_u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.GamesTable,
			Columns: []string{script.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.GamesTable,
			Columns: []string{script.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{script.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScriptUpdateOne is the builder for updating a single Script entity.
type ScriptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScriptMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptUpdateOne) SetUpdatedAt(v time.Time) *ScriptUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ScriptUpdateOne) SetName(v string) *ScriptUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableName(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEdition sets the "edition" field.
func (_u *ScriptUpdateOne) SetEdition(v string) *ScriptUpdateOne {
	_u.mutation.SetEdition(v)
	return _u
}

// SetNillableEdition sets the "edition" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableEdition(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetEdition(*v)
	}
	return _u
}

// SetCharacterIds sets the "character_ids" field.
func (_u *ScriptUpdateOne) SetCharacterIds(v []string) *ScriptUpdateOne {
	_u.mutation.SetCharacterIds(v)
	return _u
}

// AppendCharacterIds appends value to the "character_ids" field.
func (_u *ScriptUpdateOne) AppendCharacterIds(v []string) *ScriptUpdateOne {
	_u.mutation.AppendCharacterIds(v)
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *ScriptUpdateOne) SetIsSystem(v bool) *ScriptUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableIsSystem(v *bool) *ScriptUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ScriptUpdateOne) SetUserID(v int) *ScriptUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableUserID(v *int) *ScriptUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ScriptUpdateOne) ClearUserID() *ScriptUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ScriptUpdateOne) SetDeletedAt(v time.Time) *ScriptUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableDeletedAt(v *time.Time) *ScriptUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ScriptUpdateOne) ClearDeletedAt() *ScriptUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ScriptUpdateOne) SetOwnerID(id int) *ScriptUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableOwnerID(id *int) *ScriptUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ScriptUpdateOne) SetOwner(v *User) *ScriptUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (_u *ScriptUpdateOne) AddGameIDs(ids ...int) *ScriptUpdateOne {
	_u.mutation.AddGameIDs(ids...)
	return _u
}

// AddGames adds the "games" edges to the Game entity.
func (_u *ScriptUpdateOne) AddGames(v ...*Game) *ScriptUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGameIDs(ids...)
}

// Mutation returns the ScriptMutation object of the builder.
func (_u *ScriptUpdateOne) Mutation() *ScriptMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ScriptUpdateOne) ClearOwner() *ScriptUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearGames clears all "games" edges to the Game entity.
func (_u *ScriptUpdateOne) ClearGames() *ScriptUpdateOne {
	_u.mutation.ClearGames()
	return _u
}

// RemoveGameIDs removes the "games" edge to Game entities by IDs.
func (_u *ScriptUpdateOne) RemoveGameIDs(ids ...int) *ScriptUpdateOne {
	_u.mutation.RemoveGameIDs(ids...)
	return _u
}

// RemoveGames removes "games" edges to Game entities.
func (_u *ScriptUpdateOne) RemoveGames(v ...*Game) *ScriptUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGameIDs(ids...)
}

// Where appends a list predicates to the ScriptUpdate builder.
func (_u *ScriptUpdateOne) Where(ps ...predicate.Script) *ScriptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScriptUpdateOne) Select(field string, fields ...string) *ScriptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Script entity.
func (_u *ScriptUpdateOne) Save(ctx context.Context) (*Script, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptUpdateOne) SaveX(ctx context.Context) *Script {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScriptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := script.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ScriptUpdateOne) sqlSave(ctx context.Context) (_node *Script, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(script.Table, script.Columns, sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Script.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, script.FieldID)
		for _, f := range fields {
			if !script.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != script.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(script.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Edition(); ok {
		_spec.SetField(script.FieldEdition, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterIds(); ok {
		_spec.SetField(script.FieldCharacterIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCharacterIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, script.FieldCharacterIds, value)
		})
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(script.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(script.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(script.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   script.OwnerTable,
			Columns: []string{script.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   script.OwnerTable,
			Columns: []string{script.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.GamesTable,
			Columns: []string{script.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamesIDs(); len(nodes) > 0 && !_u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.GamesTable,
			Columns: []string{script.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.GamesTable,
			Columns: []string{script.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Script{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{script.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
