// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/clockkeeper/ent/game"
	"github.com/shifty11/clockkeeper/ent/script"
	"github.com/shifty11/clockkeeper/ent/user"
)

// ScriptCreate is the builder for creating a Script entity.
type ScriptCreate struct {
	config
	mutation *ScriptMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScriptCreate) SetCreatedAt(v time.Time) *ScriptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableCreatedAt(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScriptCreate) SetUpdatedAt(v time.Time) *ScriptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableUpdatedAt(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ScriptCreate) SetName(v string) *ScriptCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEdition sets the "edition" field.
func (_c *ScriptCreate) SetEdition(v string) *ScriptCreate {
	_c.mutation.SetEdition(v)
	return _c
}

// SetNillableEdition sets the "edition" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableEdition(v *string) *ScriptCreate {
	if v != nil {
		_c.SetEdition(*v)
	}
	return _c
}

// SetCharacterIds sets the "character_ids" field.
func (_c *ScriptCreate) SetCharacterIds(v []string) *ScriptCreate {
	_c.mutation.SetCharacterIds(v)
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *ScriptCreate) SetIsSystem(v bool) *ScriptCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableIsSystem(v *bool) *ScriptCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ScriptCreate) SetUserID(v int) *ScriptCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableUserID(v *int) *ScriptCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ScriptCreate) SetDeletedAt(v time.Time) *ScriptCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDeletedAt(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *ScriptCreate) SetOwnerID(id int) *ScriptCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *ScriptCreate) SetNillableOwnerID(id *int) *ScriptCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *ScriptCreate) SetOwner(v *User) *ScriptCreate {
	return _c.SetOwnerID(v.ID)
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (_c *ScriptCreate) AddGameIDs(ids ...int) *ScriptCreate {
	_c.mutation.AddGameIDs(ids...)
	return _c
}

// AddGames adds the "games" edges to the Game entity.
func (_c *ScriptCreate) AddGames(v ...*Game) *ScriptCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGameIDs(ids...)
}

// Mutation returns the ScriptMutation object of the builder.
func (_c *ScriptCreate) Mutation() *ScriptMutation {
	return _c.mutation
}

// Save creates the Script in the database.
func (_c *ScriptCreate) Save(ctx context.Context) (*Script, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScriptCreate) SaveX(ctx context.Context) *Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScriptCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := script.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := script.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Edition(); !ok {
		v := script.DefaultEdition
		_c.mutation.SetEdition(v)
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := script.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScriptCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Script.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Script.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Script.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Edition(); !ok {
		return &ValidationError{Name: "edition", err: errors.New(`ent: missing required field "Script.edition"`)}
	}
	if _, ok := _c.mutation.CharacterIds(); !ok {
		return &ValidationError{Name: "character_ids", err: errors.New(`ent: missing required field "Script.character_ids"`)}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "Script.is_system"`)}
	}
	return nil
}

func (_c *ScriptCreate) sqlSave(ctx context.Context) (*Script, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScriptCreate) createSpec() (*Script, *sqlgraph.CreateSpec) {
	var (
		_node = &Script{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(script.Table, sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(script.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(script.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Edition(); ok {
		_spec.SetField(script.FieldEdition, field.TypeString, value)
		_node.Edition = value
	}
	if value, ok := _c.mutation.CharacterIds(); ok {
		_spec.SetField(script.FieldCharacterIds, field.TypeJSON, value)
		_node.CharacterIds = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(script.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(script.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   script.OwnerTable,
			Columns: []string{script.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.GamesTable,
			Columns: []string{script.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScriptCreateBulk is the builder for creating many Script entities in bulk.
type ScriptCreateBulk struct {
	config
	err      error
	builders []*ScriptCreate
}

// Save creates the Script entities in the database.
func (_c *ScriptCreateBulk) Save(ctx context.Context) ([]*Script, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Script, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScriptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScriptCreateBulk) SaveX(ctx context.Context) []*Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
