// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID string `json:"uuid,omitempty"`
	// DiscordID holds the value of the "discord_id" field.
	DiscordID *string `json:"discord_id,omitempty"`
	// DiscordUsername holds the value of the "discord_username" field.
	DiscordUsername *string `json:"discord_username,omitempty"`
	// DiscordAvatar holds the value of the "discord_avatar" field.
	DiscordAvatar *string `json:"discord_avatar,omitempty"`
	// IsAnonymous holds the value of the "is_anonymous" field.
	IsAnonymous bool `json:"is_anonymous,omitempty"`
	// LastActiveAt holds the value of the "last_active_at" field.
	LastActiveAt time.Time `json:"last_active_at,omitempty"`
	// PlayerPresets holds the value of the "player_presets" field.
	PlayerPresets []string `json:"player_presets,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Scripts holds the value of the scripts edge.
	Scripts []*Script `json:"scripts,omitempty"`
	// Games holds the value of the games edge.
	Games []*Game `json:"games,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ScriptsOrErr returns the Scripts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ScriptsOrErr() ([]*Script, error) {
	if e.loadedTypes[0] {
		return e.Scripts, nil
	}
	return nil, &NotLoadedError{edge: "scripts"}
}

// GamesOrErr returns the Games value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) GamesOrErr() ([]*Game, error) {
	if e.loadedTypes[1] {
		return e.Games, nil
	}
	return nil, &NotLoadedError{edge: "games"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldPlayerPresets:
			values[i] = new([]byte)
		case user.FieldIsAnonymous:
			values[i] = new(sql.NullBool)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldUUID, user.FieldDiscordID, user.FieldDiscordUsername, user.FieldDiscordAvatar:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt, user.FieldLastActiveAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value.Valid {
				_m.UUID = value.String
			}
		case user.FieldDiscordID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discord_id", values[i])
			} else if value.Valid {
				_m.DiscordID = new(string)
				*_m.DiscordID = value.String
			}
		case user.FieldDiscordUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discord_username", values[i])
			} else if value.Valid {
				_m.DiscordUsername = new(string)
				*_m.DiscordUsername = value.String
			}
		case user.FieldDiscordAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discord_avatar", values[i])
			} else if value.Valid {
				_m.DiscordAvatar = new(string)
				*_m.DiscordAvatar = value.String
			}
		case user.FieldIsAnonymous:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_anonymous", values[i])
			} else if value.Valid {
				_m.IsAnonymous = value.Bool
			}
		case user.FieldLastActiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_active_at", values[i])
			} else if value.Valid {
				_m.LastActiveAt = value.Time
			}
		case user.FieldPlayerPresets:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field player_presets", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PlayerPresets); err != nil {
					return fmt.Errorf("unmarshal field player_presets: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryScripts queries the "scripts" edge of the User entity.
func (_m *User) QueryScripts() *ScriptQuery {
	return NewUserClient(_m.config).QueryScripts(_m)
}

// QueryGames queries the "games" edge of the User entity.
func (_m *User) QueryGames() *GameQuery {
	return NewUserClient(_m.config).QueryGames(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("uuid=")
	builder.WriteString(_m.UUID)
	builder.WriteString(", ")
	if v := _m.DiscordID; v != nil {
		builder.WriteString("discord_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DiscordUsername; v != nil {
		builder.WriteString("discord_username=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DiscordAvatar; v != nil {
		builder.WriteString("discord_avatar=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_anonymous=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAnonymous))
	builder.WriteString(", ")
	builder.WriteString("last_active_at=")
	builder.WriteString(_m.LastActiveAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("player_presets=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlayerPresets))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
