// Code generated by ent, DO NOT EDIT.

package phase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shifty11/clockkeeper/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Phase {
	return predicate.Phase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Phase {
	return predicate.Phase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Phase {
	return predicate.Phase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Phase {
	return predicate.Phase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Phase {
	return predicate.Phase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Phase {
	return predicate.Phase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Phase {
	return predicate.Phase(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldUpdatedAt, v))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldGameID, v))
}

// RoundNumber applies equality check predicate on the "round_number" field. It's identical to RoundNumberEQ.
func RoundNumber(v int) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldRoundNumber, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Phase {
	return predicate.Phase(sql.FieldLTE(FieldUpdatedAt, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int) predicate.Phase {
	return predicate.Phase(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int) predicate.Phase {
	return predicate.Phase(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int) predicate.Phase {
	return predicate.Phase(sql.FieldNotIn(FieldGameID, vs...))
}

// RoundNumberEQ applies the EQ predicate on the "round_number" field.
func RoundNumberEQ(v int) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldRoundNumber, v))
}

// RoundNumberNEQ applies the NEQ predicate on the "round_number" field.
func RoundNumberNEQ(v int) predicate.Phase {
	return predicate.Phase(sql.FieldNEQ(FieldRoundNumber, v))
}

// RoundNumberIn applies the In predicate on the "round_number" field.
func RoundNumberIn(vs ...int) predicate.Phase {
	return predicate.Phase(sql.FieldIn(FieldRoundNumber, vs...))
}

// RoundNumberNotIn applies the NotIn predicate on the "round_number" field.
func RoundNumberNotIn(vs ...int) predicate.Phase {
	return predicate.Phase(sql.FieldNotIn(FieldRoundNumber, vs...))
}

// RoundNumberGT applies the GT predicate on the "round_number" field.
func RoundNumberGT(v int) predicate.Phase {
	return predicate.Phase(sql.FieldGT(FieldRoundNumber, v))
}

// RoundNumberGTE applies the GTE predicate on the "round_number" field.
func RoundNumberGTE(v int) predicate.Phase {
	return predicate.Phase(sql.FieldGTE(FieldRoundNumber, v))
}

// RoundNumberLT applies the LT predicate on the "round_number" field.
func RoundNumberLT(v int) predicate.Phase {
	return predicate.Phase(sql.FieldLT(FieldRoundNumber, v))
}

// RoundNumberLTE applies the LTE predicate on the "round_number" field.
func RoundNumberLTE(v int) predicate.Phase {
	return predicate.Phase(sql.FieldLTE(FieldRoundNumber, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Phase {
	return predicate.Phase(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Phase {
	return predicate.Phase(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Phase {
	return predicate.Phase(sql.FieldNotIn(FieldType, vs...))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Phase {
	return predicate.Phase(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Phase {
	return predicate.Phase(sql.FieldNEQ(FieldIsActive, v))
}

// CompletedActionsIsNil applies the IsNil predicate on the "completed_actions" field.
func CompletedActionsIsNil() predicate.Phase {
	return predicate.Phase(sql.FieldIsNull(FieldCompletedActions))
}

// CompletedActionsNotNil applies the NotNil predicate on the "completed_actions" field.
func CompletedActionsNotNil() predicate.Phase {
	return predicate.Phase(sql.FieldNotNull(FieldCompletedActions))
}

// CharacterAlignmentsIsNil applies the IsNil predicate on the "character_alignments" field.
func CharacterAlignmentsIsNil() predicate.Phase {
	return predicate.Phase(sql.FieldIsNull(FieldCharacterAlignments))
}

// CharacterAlignmentsNotNil applies the NotNil predicate on the "character_alignments" field.
func CharacterAlignmentsNotNil() predicate.Phase {
	return predicate.Phase(sql.FieldNotNull(FieldCharacterAlignments))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.Phase {
	return predicate.Phase(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.Phase {
	return predicate.Phase(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeaths applies the HasEdge predicate on the "deaths" edge.
func HasDeaths() predicate.Phase {
	return predicate.Phase(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeathsTable, DeathsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeathsWith applies the HasEdge predicate on the "deaths" edge with a given conditions (other predicates).
func HasDeathsWith(preds ...predicate.Death) predicate.Phase {
	return predicate.Phase(func(s *sql.Selector) {
		step := newDeathsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Phase) predicate.Phase {
	return predicate.Phase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Phase) predicate.Phase {
	return predicate.Phase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Phase) predicate.Phase {
	return predicate.Phase(sql.NotPredicates(p))
}
