-- Create "scripts" table
CREATE TABLE "scripts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "edition" character varying NOT NULL DEFAULT 'custom',
  "character_ids" jsonb NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "scripts_users_scripts" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "games" table
CREATE TABLE "games" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "player_count" bigint NOT NULL,
  "selected_roles" jsonb NOT NULL,
  "state" character varying NOT NULL DEFAULT 'setup',
  "script_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "games_scripts_games" FOREIGN KEY ("script_id") REFERENCES "scripts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
