// Code generated by ent, DO NOT EDIT.

package game

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the game type in the database.
	Label = "game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldScriptID holds the string denoting the script_id field in the database.
	FieldScriptID = "script_id"
	// FieldPlayerCount holds the string denoting the player_count field in the database.
	FieldPlayerCount = "player_count"
	// FieldTravellerCount holds the string denoting the traveller_count field in the database.
	FieldTravellerCount = "traveller_count"
	// FieldSelectedRoles holds the string denoting the selected_roles field in the database.
	FieldSelectedRoles = "selected_roles"
	// FieldSelectedTravellers holds the string denoting the selected_travellers field in the database.
	FieldSelectedTravellers = "selected_travellers"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// EdgeScript holds the string denoting the script edge name in mutations.
	EdgeScript = "script"
	// Table holds the table name of the game in the database.
	Table = "games"
	// ScriptTable is the table that holds the script relation/edge.
	ScriptTable = "games"
	// ScriptInverseTable is the table name for the Script entity.
	// It exists in this package in order to avoid circular dependency with the "script" package.
	ScriptInverseTable = "scripts"
	// ScriptColumn is the table column denoting the script relation/edge.
	ScriptColumn = "script_id"
)

// Columns holds all SQL columns for game fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldScriptID,
	FieldPlayerCount,
	FieldTravellerCount,
	FieldSelectedRoles,
	FieldSelectedTravellers,
	FieldState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PlayerCountValidator is a validator for the "player_count" field. It is called by the builders before save.
	PlayerCountValidator func(int) error
	// DefaultTravellerCount holds the default value on creation for the "traveller_count" field.
	DefaultTravellerCount int
	// TravellerCountValidator is a validator for the "traveller_count" field. It is called by the builders before save.
	TravellerCountValidator func(int) error
)

// State defines the type for the "state" enum field.
type State string

// StateSetup is the default value of the State enum.
const DefaultState = StateSetup

// State values.
const (
	StateSetup      State = "setup"
	StateInProgress State = "in_progress"
	StateCompleted  State = "completed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateSetup, StateInProgress, StateCompleted:
		return nil
	default:
		return fmt.Errorf("game: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Game queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScriptID orders the results by the script_id field.
func ByScriptID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScriptID, opts...).ToFunc()
}

// ByPlayerCount orders the results by the player_count field.
func ByPlayerCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerCount, opts...).ToFunc()
}

// ByTravellerCount orders the results by the traveller_count field.
func ByTravellerCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTravellerCount, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByScriptField orders the results by script field.
func ByScriptField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScriptStep(), sql.OrderByField(field, opts...))
	}
}
func newScriptStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScriptInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ScriptTable, ScriptColumn),
	)
}
