// Code generated by ent, DO NOT EDIT.

package game

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shifty11/clockkeeper/ent/schema"
)

const (
	// Label holds the string label denoting the game type in the database.
	Label = "game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldScriptID holds the string denoting the script_id field in the database.
	FieldScriptID = "script_id"
	// FieldPlayerCount holds the string denoting the player_count field in the database.
	FieldPlayerCount = "player_count"
	// FieldTravellerCount holds the string denoting the traveller_count field in the database.
	FieldTravellerCount = "traveller_count"
	// FieldSelectedRoles holds the string denoting the selected_roles field in the database.
	FieldSelectedRoles = "selected_roles"
	// FieldSelectedTravellers holds the string denoting the selected_travellers field in the database.
	FieldSelectedTravellers = "selected_travellers"
	// FieldExtraCharacters holds the string denoting the extra_characters field in the database.
	FieldExtraCharacters = "extra_characters"
	// FieldSelectedBluffs holds the string denoting the selected_bluffs field in the database.
	FieldSelectedBluffs = "selected_bluffs"
	// FieldTravellerAlignments holds the string denoting the traveller_alignments field in the database.
	FieldTravellerAlignments = "traveller_alignments"
	// FieldGrimoirePositions holds the string denoting the grimoire_positions field in the database.
	FieldGrimoirePositions = "grimoire_positions"
	// FieldGrimoirePlayerNames holds the string denoting the grimoire_player_names field in the database.
	FieldGrimoirePlayerNames = "grimoire_player_names"
	// FieldGrimoireGameNotes holds the string denoting the grimoire_game_notes field in the database.
	FieldGrimoireGameNotes = "grimoire_game_notes"
	// FieldGrimoireRoundNotes holds the string denoting the grimoire_round_notes field in the database.
	FieldGrimoireRoundNotes = "grimoire_round_notes"
	// FieldBagSubstitutions holds the string denoting the bag_substitutions field in the database.
	FieldBagSubstitutions = "bag_substitutions"
	// FieldGrimoireReminderAttachments holds the string denoting the grimoire_reminder_attachments field in the database.
	FieldGrimoireReminderAttachments = "grimoire_reminder_attachments"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeScript holds the string denoting the script edge name in mutations.
	EdgeScript = "script"
	// EdgePhases holds the string denoting the phases edge name in mutations.
	EdgePhases = "phases"
	// Table holds the table name of the game in the database.
	Table = "games"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "games"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
	// ScriptTable is the table that holds the script relation/edge.
	ScriptTable = "games"
	// ScriptInverseTable is the table name for the Script entity.
	// It exists in this package in order to avoid circular dependency with the "script" package.
	ScriptInverseTable = "scripts"
	// ScriptColumn is the table column denoting the script relation/edge.
	ScriptColumn = "script_id"
	// PhasesTable is the table that holds the phases relation/edge.
	PhasesTable = "phases"
	// PhasesInverseTable is the table name for the Phase entity.
	// It exists in this package in order to avoid circular dependency with the "phase" package.
	PhasesInverseTable = "phases"
	// PhasesColumn is the table column denoting the phases relation/edge.
	PhasesColumn = "game_id"
)

// Columns holds all SQL columns for game fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldUserID,
	FieldScriptID,
	FieldPlayerCount,
	FieldTravellerCount,
	FieldSelectedRoles,
	FieldSelectedTravellers,
	FieldExtraCharacters,
	FieldSelectedBluffs,
	FieldTravellerAlignments,
	FieldGrimoirePositions,
	FieldGrimoirePlayerNames,
	FieldGrimoireGameNotes,
	FieldGrimoireRoundNotes,
	FieldBagSubstitutions,
	FieldGrimoireReminderAttachments,
	FieldState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// PlayerCountValidator is a validator for the "player_count" field. It is called by the builders before save.
	PlayerCountValidator func(int) error
	// DefaultTravellerCount holds the default value on creation for the "traveller_count" field.
	DefaultTravellerCount int
	// TravellerCountValidator is a validator for the "traveller_count" field. It is called by the builders before save.
	TravellerCountValidator func(int) error
	// DefaultExtraCharacters holds the default value on creation for the "extra_characters" field.
	DefaultExtraCharacters []string
	// DefaultSelectedBluffs holds the default value on creation for the "selected_bluffs" field.
	DefaultSelectedBluffs []string
	// DefaultTravellerAlignments holds the default value on creation for the "traveller_alignments" field.
	DefaultTravellerAlignments map[string]schema.TravellerAlignment
	// DefaultGrimoirePositions holds the default value on creation for the "grimoire_positions" field.
	DefaultGrimoirePositions map[string]schema.GrimoirePosition
	// DefaultGrimoirePlayerNames holds the default value on creation for the "grimoire_player_names" field.
	DefaultGrimoirePlayerNames map[string]string
	// DefaultGrimoireGameNotes holds the default value on creation for the "grimoire_game_notes" field.
	DefaultGrimoireGameNotes map[string]string
	// DefaultGrimoireRoundNotes holds the default value on creation for the "grimoire_round_notes" field.
	DefaultGrimoireRoundNotes map[string]string
	// DefaultBagSubstitutions holds the default value on creation for the "bag_substitutions" field.
	DefaultBagSubstitutions []schema.GameBagSubstitution
	// DefaultGrimoireReminderAttachments holds the default value on creation for the "grimoire_reminder_attachments" field.
	DefaultGrimoireReminderAttachments map[string]string
)

// State defines the type for the "state" enum field.
type State string

// StateSetup is the default value of the State enum.
const DefaultState = StateSetup

// State values.
const (
	StateSetup      State = "setup"
	StateInProgress State = "in_progress"
	StateCompleted  State = "completed"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateSetup, StateInProgress, StateCompleted:
		return nil
	default:
		return fmt.Errorf("game: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Game queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByScriptID orders the results by the script_id field.
func ByScriptID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScriptID, opts...).ToFunc()
}

// ByPlayerCount orders the results by the player_count field.
func ByPlayerCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerCount, opts...).ToFunc()
}

// ByTravellerCount orders the results by the traveller_count field.
func ByTravellerCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTravellerCount, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByScriptField orders the results by script field.
func ByScriptField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScriptStep(), sql.OrderByField(field, opts...))
	}
}

// ByPhasesCount orders the results by phases count.
func ByPhasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPhasesStep(), opts...)
	}
}

// ByPhases orders the results by phases terms.
func ByPhases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPhasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newScriptStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScriptInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ScriptTable, ScriptColumn),
	)
}
func newPhasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PhasesTable, PhasesColumn),
	)
}
