// Code generated by ent, DO NOT EDIT.

package game

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScriptID applies equality check predicate on the "script_id" field. It's identical to ScriptIDEQ.
func ScriptID(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldScriptID, v))
}

// PlayerCount applies equality check predicate on the "player_count" field. It's identical to PlayerCountEQ.
func PlayerCount(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlayerCount, v))
}

// TravellerCount applies equality check predicate on the "traveller_count" field. It's identical to TravellerCountEQ.
func TravellerCount(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldTravellerCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldUpdatedAt, v))
}

// ScriptIDEQ applies the EQ predicate on the "script_id" field.
func ScriptIDEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldScriptID, v))
}

// ScriptIDNEQ applies the NEQ predicate on the "script_id" field.
func ScriptIDNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldScriptID, v))
}

// ScriptIDIn applies the In predicate on the "script_id" field.
func ScriptIDIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldScriptID, vs...))
}

// ScriptIDNotIn applies the NotIn predicate on the "script_id" field.
func ScriptIDNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldScriptID, vs...))
}

// PlayerCountEQ applies the EQ predicate on the "player_count" field.
func PlayerCountEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlayerCount, v))
}

// PlayerCountNEQ applies the NEQ predicate on the "player_count" field.
func PlayerCountNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldPlayerCount, v))
}

// PlayerCountIn applies the In predicate on the "player_count" field.
func PlayerCountIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldPlayerCount, vs...))
}

// PlayerCountNotIn applies the NotIn predicate on the "player_count" field.
func PlayerCountNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldPlayerCount, vs...))
}

// PlayerCountGT applies the GT predicate on the "player_count" field.
func PlayerCountGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldPlayerCount, v))
}

// PlayerCountGTE applies the GTE predicate on the "player_count" field.
func PlayerCountGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldPlayerCount, v))
}

// PlayerCountLT applies the LT predicate on the "player_count" field.
func PlayerCountLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldPlayerCount, v))
}

// PlayerCountLTE applies the LTE predicate on the "player_count" field.
func PlayerCountLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldPlayerCount, v))
}

// TravellerCountEQ applies the EQ predicate on the "traveller_count" field.
func TravellerCountEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldTravellerCount, v))
}

// TravellerCountNEQ applies the NEQ predicate on the "traveller_count" field.
func TravellerCountNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldTravellerCount, v))
}

// TravellerCountIn applies the In predicate on the "traveller_count" field.
func TravellerCountIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldTravellerCount, vs...))
}

// TravellerCountNotIn applies the NotIn predicate on the "traveller_count" field.
func TravellerCountNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldTravellerCount, vs...))
}

// TravellerCountGT applies the GT predicate on the "traveller_count" field.
func TravellerCountGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldTravellerCount, v))
}

// TravellerCountGTE applies the GTE predicate on the "traveller_count" field.
func TravellerCountGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldTravellerCount, v))
}

// TravellerCountLT applies the LT predicate on the "traveller_count" field.
func TravellerCountLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldTravellerCount, v))
}

// TravellerCountLTE applies the LTE predicate on the "traveller_count" field.
func TravellerCountLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldTravellerCount, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldState, vs...))
}

// HasScript applies the HasEdge predicate on the "script" edge.
func HasScript() predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScriptTable, ScriptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScriptWith applies the HasEdge predicate on the "script" edge with a given conditions (other predicates).
func HasScriptWith(preds ...predicate.Script) predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := newScriptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Game) predicate.Game {
	return predicate.Game(sql.NotPredicates(p))
}
