// Code generated by ent, DO NOT EDIT.

package game

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shifty11/clockkeeper/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldName, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUserID, v))
}

// ScriptID applies equality check predicate on the "script_id" field. It's identical to ScriptIDEQ.
func ScriptID(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldScriptID, v))
}

// PlayerCount applies equality check predicate on the "player_count" field. It's identical to PlayerCountEQ.
func PlayerCount(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlayerCount, v))
}

// TravellerCount applies equality check predicate on the "traveller_count" field. It's identical to TravellerCountEQ.
func TravellerCount(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldTravellerCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldName, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldUserID, vs...))
}

// ScriptIDEQ applies the EQ predicate on the "script_id" field.
func ScriptIDEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldScriptID, v))
}

// ScriptIDNEQ applies the NEQ predicate on the "script_id" field.
func ScriptIDNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldScriptID, v))
}

// ScriptIDIn applies the In predicate on the "script_id" field.
func ScriptIDIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldScriptID, vs...))
}

// ScriptIDNotIn applies the NotIn predicate on the "script_id" field.
func ScriptIDNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldScriptID, vs...))
}

// PlayerCountEQ applies the EQ predicate on the "player_count" field.
func PlayerCountEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlayerCount, v))
}

// PlayerCountNEQ applies the NEQ predicate on the "player_count" field.
func PlayerCountNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldPlayerCount, v))
}

// PlayerCountIn applies the In predicate on the "player_count" field.
func PlayerCountIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldPlayerCount, vs...))
}

// PlayerCountNotIn applies the NotIn predicate on the "player_count" field.
func PlayerCountNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldPlayerCount, vs...))
}

// PlayerCountGT applies the GT predicate on the "player_count" field.
func PlayerCountGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldPlayerCount, v))
}

// PlayerCountGTE applies the GTE predicate on the "player_count" field.
func PlayerCountGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldPlayerCount, v))
}

// PlayerCountLT applies the LT predicate on the "player_count" field.
func PlayerCountLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldPlayerCount, v))
}

// PlayerCountLTE applies the LTE predicate on the "player_count" field.
func PlayerCountLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldPlayerCount, v))
}

// TravellerCountEQ applies the EQ predicate on the "traveller_count" field.
func TravellerCountEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldTravellerCount, v))
}

// TravellerCountNEQ applies the NEQ predicate on the "traveller_count" field.
func TravellerCountNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldTravellerCount, v))
}

// TravellerCountIn applies the In predicate on the "traveller_count" field.
func TravellerCountIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldTravellerCount, vs...))
}

// TravellerCountNotIn applies the NotIn predicate on the "traveller_count" field.
func TravellerCountNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldTravellerCount, vs...))
}

// TravellerCountGT applies the GT predicate on the "traveller_count" field.
func TravellerCountGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldTravellerCount, v))
}

// TravellerCountGTE applies the GTE predicate on the "traveller_count" field.
func TravellerCountGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldTravellerCount, v))
}

// TravellerCountLT applies the LT predicate on the "traveller_count" field.
func TravellerCountLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldTravellerCount, v))
}

// TravellerCountLTE applies the LTE predicate on the "traveller_count" field.
func TravellerCountLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldTravellerCount, v))
}

// ExtraCharactersIsNil applies the IsNil predicate on the "extra_characters" field.
func ExtraCharactersIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldExtraCharacters))
}

// ExtraCharactersNotNil applies the NotNil predicate on the "extra_characters" field.
func ExtraCharactersNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldExtraCharacters))
}

// SelectedBluffsIsNil applies the IsNil predicate on the "selected_bluffs" field.
func SelectedBluffsIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldSelectedBluffs))
}

// SelectedBluffsNotNil applies the NotNil predicate on the "selected_bluffs" field.
func SelectedBluffsNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldSelectedBluffs))
}

// TravellerAlignmentsIsNil applies the IsNil predicate on the "traveller_alignments" field.
func TravellerAlignmentsIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldTravellerAlignments))
}

// TravellerAlignmentsNotNil applies the NotNil predicate on the "traveller_alignments" field.
func TravellerAlignmentsNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldTravellerAlignments))
}

// GrimoirePositionsIsNil applies the IsNil predicate on the "grimoire_positions" field.
func GrimoirePositionsIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldGrimoirePositions))
}

// GrimoirePositionsNotNil applies the NotNil predicate on the "grimoire_positions" field.
func GrimoirePositionsNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldGrimoirePositions))
}

// GrimoirePlayerNamesIsNil applies the IsNil predicate on the "grimoire_player_names" field.
func GrimoirePlayerNamesIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldGrimoirePlayerNames))
}

// GrimoirePlayerNamesNotNil applies the NotNil predicate on the "grimoire_player_names" field.
func GrimoirePlayerNamesNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldGrimoirePlayerNames))
}

// GrimoireGameNotesIsNil applies the IsNil predicate on the "grimoire_game_notes" field.
func GrimoireGameNotesIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldGrimoireGameNotes))
}

// GrimoireGameNotesNotNil applies the NotNil predicate on the "grimoire_game_notes" field.
func GrimoireGameNotesNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldGrimoireGameNotes))
}

// GrimoireRoundNotesIsNil applies the IsNil predicate on the "grimoire_round_notes" field.
func GrimoireRoundNotesIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldGrimoireRoundNotes))
}

// GrimoireRoundNotesNotNil applies the NotNil predicate on the "grimoire_round_notes" field.
func GrimoireRoundNotesNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldGrimoireRoundNotes))
}

// BagSubstitutionsIsNil applies the IsNil predicate on the "bag_substitutions" field.
func BagSubstitutionsIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldBagSubstitutions))
}

// BagSubstitutionsNotNil applies the NotNil predicate on the "bag_substitutions" field.
func BagSubstitutionsNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldBagSubstitutions))
}

// GrimoireReminderAttachmentsIsNil applies the IsNil predicate on the "grimoire_reminder_attachments" field.
func GrimoireReminderAttachmentsIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldGrimoireReminderAttachments))
}

// GrimoireReminderAttachmentsNotNil applies the NotNil predicate on the "grimoire_reminder_attachments" field.
func GrimoireReminderAttachmentsNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldGrimoireReminderAttachments))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldState, vs...))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasScript applies the HasEdge predicate on the "script" edge.
func HasScript() predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScriptTable, ScriptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScriptWith applies the HasEdge predicate on the "script" edge with a given conditions (other predicates).
func HasScriptWith(preds ...predicate.Script) predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := newScriptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPhases applies the HasEdge predicate on the "phases" edge.
func HasPhases() predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PhasesTable, PhasesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPhasesWith applies the HasEdge predicate on the "phases" edge with a given conditions (other predicates).
func HasPhasesWith(preds ...predicate.Phase) predicate.Game {
	return predicate.Game(func(s *sql.Selector) {
		step := newPhasesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Game) predicate.Game {
	return predicate.Game(sql.NotPredicates(p))
}
