// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldDiscordID holds the string denoting the discord_id field in the database.
	FieldDiscordID = "discord_id"
	// FieldDiscordUsername holds the string denoting the discord_username field in the database.
	FieldDiscordUsername = "discord_username"
	// FieldDiscordAvatar holds the string denoting the discord_avatar field in the database.
	FieldDiscordAvatar = "discord_avatar"
	// FieldIsAnonymous holds the string denoting the is_anonymous field in the database.
	FieldIsAnonymous = "is_anonymous"
	// FieldLastActiveAt holds the string denoting the last_active_at field in the database.
	FieldLastActiveAt = "last_active_at"
	// FieldPlayerPresets holds the string denoting the player_presets field in the database.
	FieldPlayerPresets = "player_presets"
	// EdgeScripts holds the string denoting the scripts edge name in mutations.
	EdgeScripts = "scripts"
	// EdgeGames holds the string denoting the games edge name in mutations.
	EdgeGames = "games"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ScriptsTable is the table that holds the scripts relation/edge.
	ScriptsTable = "scripts"
	// ScriptsInverseTable is the table name for the Script entity.
	// It exists in this package in order to avoid circular dependency with the "script" package.
	ScriptsInverseTable = "scripts"
	// ScriptsColumn is the table column denoting the scripts relation/edge.
	ScriptsColumn = "user_id"
	// GamesTable is the table that holds the games relation/edge.
	GamesTable = "games"
	// GamesInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	GamesInverseTable = "games"
	// GamesColumn is the table column denoting the games relation/edge.
	GamesColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUUID,
	FieldDiscordID,
	FieldDiscordUsername,
	FieldDiscordAvatar,
	FieldIsAnonymous,
	FieldLastActiveAt,
	FieldPlayerPresets,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultUUID holds the default value on creation for the "uuid" field.
	DefaultUUID func() string
	// UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	UUIDValidator func(string) error
	// DefaultIsAnonymous holds the default value on creation for the "is_anonymous" field.
	DefaultIsAnonymous bool
	// DefaultLastActiveAt holds the default value on creation for the "last_active_at" field.
	DefaultLastActiveAt func() time.Time
	// DefaultPlayerPresets holds the default value on creation for the "player_presets" field.
	DefaultPlayerPresets []string
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUUID orders the results by the uuid field.
func ByUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUUID, opts...).ToFunc()
}

// ByDiscordID orders the results by the discord_id field.
func ByDiscordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscordID, opts...).ToFunc()
}

// ByDiscordUsername orders the results by the discord_username field.
func ByDiscordUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscordUsername, opts...).ToFunc()
}

// ByDiscordAvatar orders the results by the discord_avatar field.
func ByDiscordAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscordAvatar, opts...).ToFunc()
}

// ByIsAnonymous orders the results by the is_anonymous field.
func ByIsAnonymous(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAnonymous, opts...).ToFunc()
}

// ByLastActiveAt orders the results by the last_active_at field.
func ByLastActiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActiveAt, opts...).ToFunc()
}

// ByScriptsCount orders the results by scripts count.
func ByScriptsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newScriptsStep(), opts...)
	}
}

// ByScripts orders the results by scripts terms.
func ByScripts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScriptsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGamesCount orders the results by games count.
func ByGamesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGamesStep(), opts...)
	}
}

// ByGames orders the results by games terms.
func ByGames(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGamesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newScriptsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScriptsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ScriptsTable, ScriptsColumn),
	)
}
func newGamesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GamesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GamesTable, GamesColumn),
	)
}
